use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::parser::{
	EnumValues, MethodDef, OneOfBody, OneOfDiscriminatorValue, ParamDef, ParseResult,
};
use crate::transforms::enums::{self, EnumDef};
use crate::transforms::parameters::BodyEncoding;
use crate::transforms::responses::{
	component_ref_type, component_schema_to_rust_name, resolve_response_field_type,
	ResponseFieldDef, ResponseSchema,
};
use crate::transforms::types::schema_to_rust_type;
use crate::utils::deref;
use crate::utils::naming::{method_type_prefix, sanitize_ident};

/// Emit the types file (params, bodies, response aliases) for all groups.
pub fn emit_types(
	parsed: &ParseResult,
	root: &Value,
	output_dir: &str,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(8192);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();

	// Check if any type uses HashMap (params, body, or component schemas)
	let needs_hashmap = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			m.query_params
				.iter()
				.chain(m.body_params.iter())
				.any(|p| p.rust_type.contains("HashMap"))
		})
	}) || parsed.component_schemas.values().any(|schema| {
		schema
			.get("properties")
			.and_then(|v| v.as_object())
			.is_some_and(|props| {
				props.values().any(|prop_schema| {
					let resolved = deref::deref(root, prop_schema);
					let (ty, _) = schema_to_rust_type(root, resolved);
					ty.contains("HashMap")
				})
			})
	});
	if needs_hashmap {
		writeln!(out, "use std::collections::HashMap;").unwrap();
	}

	// Check if any type uses StringOrInt (in params, body, responses, or component schemas)
	let needs_string_or_int =
		parsed.groups.iter().any(|g| {
			g.methods.iter().any(|m| {
				let in_params = m
					.path_params
					.iter()
					.chain(m.query_params.iter())
					.chain(m.body_params.iter())
					.any(|p| p.rust_type.contains("StringOrInt"));
				let in_response = response_uses_string_or_int(&m.response_schema);
				in_params || in_response
			})
		}) || component_schemas_use_string_or_int(&parsed.component_schemas, root);
	if needs_string_or_int {
		writeln!(out, "use crate::runtime::StringOrInt;").unwrap();
	}

	writeln!(out).unwrap();

	// Emit component schemas (shared types referenced by multiple responses)
	let used_components = collect_used_component_schemas(parsed);
	if !used_components.is_empty() {
		writeln!(out, "// ── Component Schemas ──").unwrap();
		writeln!(out).unwrap();
		for name in &used_components {
			if let Some(schema) = parsed.component_schemas.get(name.as_str()) {
				emit_component_schema(&mut out, name, schema, root);
			}
		}
	}

	// Emit enum type definitions
	let enum_code = enums::emit_enum_definitions(enum_map);
	if !enum_code.is_empty() {
		out.push_str(&enum_code);
	}

	for group in &parsed.groups {
		for method in &group.methods {
			let prefix = method_type_prefix(&group.name, &method.name);

			// Params struct (only optional query parameters; required ones become direct args)
			let optional_query: Vec<_> = method
				.query_params
				.iter()
				.filter(|p| !p.required)
				.cloned()
				.collect();
			if !optional_query.is_empty() {
				emit_params_struct(&mut out, &prefix, &optional_query, enum_map);
			}

			// Body struct (skip for raw body — those take serde_json::Value directly)
			if method.has_body && !method.is_raw_body {
				if let Some(ref one_of) = method.one_of_body {
					emit_one_of_body_enum(&mut out, &prefix, one_of, enum_map);
				} else {
					match method.body_encoding {
						BodyEncoding::Multipart => {
							emit_multipart_body_struct(
								&mut out,
								&prefix,
								&method.body_params,
								enum_map,
							);
						}
						_ => {
							emit_body_struct(&mut out, &prefix, &method.body_params, enum_map);
						}
					}
				}
			}

			// Response type
			emit_response_type(&mut out, &prefix, &method.response_schema);
		}
	}

	let path = dir.join("types.rs");
	fs::write(&path, &out).expect("failed to write types.rs");
	eprintln!("  wrote {}", path.display());
}

/// Check whether any response type references StringOrInt.
fn response_uses_string_or_int(schema: &ResponseSchema) -> bool {
	match schema {
		ResponseSchema::Alias(ty) => ty.contains("StringOrInt"),
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => {
			fields.iter().any(|f| f.rust_type.contains("StringOrInt"))
				|| nested_structs
					.iter()
					.any(|(_, fs)| fs.iter().any(|f| f.rust_type.contains("StringOrInt")))
		}
	}
}

/// Check whether any used component schema resolves to StringOrInt.
fn component_schemas_use_string_or_int(
	component_schemas: &BTreeMap<String, Value>,
	root: &Value,
) -> bool {
	component_schemas.values().any(|schema| {
		let (ty, _) = schema_to_rust_type(root, schema);
		ty.contains("StringOrInt")
	})
}

/// Collect the set of component schema original names that are actually referenced by response types.
/// Returns original schema names (e.g. `Resp_SystemInfo`), not Rust names.
fn collect_used_component_schemas(parsed: &ParseResult) -> Vec<String> {
	use std::collections::BTreeSet;

	// Build a reverse map: Rust name → original name
	let rust_to_original: BTreeMap<String, String> = parsed
		.component_schemas
		.keys()
		.map(|name| (component_schema_to_rust_name(name), name.clone()))
		.collect();

	let mut used_rust_names = BTreeSet::new();
	for group in &parsed.groups {
		for method in &group.methods {
			collect_component_refs_from_response(
				&method.response_schema,
				&rust_to_original,
				&mut used_rust_names,
			);
		}
	}

	// Map back to original names, preserving order
	used_rust_names
		.into_iter()
		.filter_map(|rust_name| rust_to_original.get(&rust_name).cloned())
		.collect()
}

/// Walk a ResponseSchema and collect Rust type names that match component schemas.
fn collect_component_refs_from_response(
	schema: &ResponseSchema,
	rust_to_original: &BTreeMap<String, String>,
	used: &mut std::collections::BTreeSet<String>,
) {
	let fields_iter: Box<dyn Iterator<Item = &ResponseFieldDef>> = match schema {
		ResponseSchema::Alias(_) => return,
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => Box::new(
			fields
				.iter()
				.chain(nested_structs.iter().flat_map(|(_, fs)| fs.iter())),
		),
	};
	for field in fields_iter {
		let ty = &field.rust_type;
		let inner = ty
			.strip_prefix("Vec<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(ty);
		let inner = inner
			.strip_prefix("Option<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(inner);
		if rust_to_original.contains_key(inner) {
			used.insert(inner.to_string());
		}
	}
}

/// Emit a component schema as a Rust type (struct, type alias, etc).
fn emit_component_schema(out: &mut String, name: &str, schema: &Value, root: &Value) {
	let rust_name = component_schema_to_rust_name(name);

	// Check for union types like ["string", "integer"] → use type alias to StringOrInt
	if let Some(type_arr) = schema.get("type").and_then(|v| v.as_array()) {
		let non_null: Vec<&str> = type_arr
			.iter()
			.filter_map(|v| v.as_str())
			.filter(|s| *s != "null")
			.collect();
		let mut sorted = non_null.clone();
		sorted.sort();
		if sorted == ["integer", "string"] {
			writeln!(out, "pub type {rust_name} = StringOrInt;").unwrap();
			writeln!(out).unwrap();
			return;
		}
		// Single primitive type
		if non_null.len() == 1 {
			let alias = match non_null[0] {
				"integer" => "i64",
				"string" => "String",
				"number" => "f64",
				"boolean" => "bool",
				_ => "serde_json::Value",
			};
			writeln!(out, "pub type {rust_name} = {alias};").unwrap();
			writeln!(out).unwrap();
			return;
		}
	}

	// Single type: integer → type alias
	if let Some(type_str) = schema.get("type").and_then(|v| v.as_str()) {
		match type_str {
			"integer" => {
				writeln!(out, "pub type {rust_name} = i64;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"string" => {
				writeln!(out, "pub type {rust_name} = String;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"number" => {
				writeln!(out, "pub type {rust_name} = f64;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"boolean" => {
				writeln!(out, "pub type {rust_name} = bool;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"object" => {
				// Fall through to struct generation below
			}
			_ => {
				writeln!(out, "pub type {rust_name} = serde_json::Value;").unwrap();
				writeln!(out).unwrap();
				return;
			}
		}
	}

	// Object with properties → generate struct
	let properties = match schema.get("properties").and_then(|v| v.as_object()) {
		Some(p) if !p.is_empty() => p,
		_ => {
			// Object without properties or no type
			writeln!(out, "pub type {rust_name} = serde_json::Value;").unwrap();
			writeln!(out).unwrap();
			return;
		}
	};

	let required_fields: Vec<String> = schema
		.get("required")
		.and_then(|v| v.as_array())
		.map(|arr| {
			arr.iter()
				.filter_map(|v| v.as_str().map(String::from))
				.collect()
		})
		.unwrap_or_default();

	let mut nested_structs: Vec<(String, Vec<ResponseFieldDef>)> = Vec::new();

	writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
	writeln!(out, "pub struct {rust_name} {{").unwrap();

	for (prop_name, prop_schema) in properties {
		let field_name = sanitize_ident(prop_name);
		let required = required_fields.contains(prop_name);

		// Resolve type — check for nested $ref first
		let rust_type = if let Some(comp_type) = component_ref_type(prop_schema) {
			comp_type
		} else {
			let resolved = deref::deref(root, prop_schema);
			resolve_response_field_type(root, resolved, &rust_name, prop_name, &mut nested_structs)
		};

		let needs_rename =
			field_name != *prop_name || prop_name.contains('-') || field_name.starts_with("r#");

		if required {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{prop_name}\")]").unwrap();
			}
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		} else {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{prop_name}\", default)]").unwrap();
			} else {
				writeln!(out, "\t#[serde(default)]").unwrap();
			}
			let rust_type = optionalize(&rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// Emit nested structs generated for inline object properties
	for (struct_name, fields) in &nested_structs {
		emit_response_struct(out, struct_name, fields);
	}
}

/// Resolve the Rust type for a param, using enum type if available.
fn resolve_param_type(
	param: &ParamDef,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) -> String {
	if let Some(ref ev) = param.enum_values {
		if let Some(type_name) = enums::lookup_enum_type(enum_map, &param.api_name, ev) {
			return type_name;
		}
	}
	param.rust_type.clone()
}

/// Emit a params struct for query parameters.
fn emit_params_struct(
	out: &mut String,
	prefix: &str,
	params: &[ParamDef],
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let struct_name = format!("{prefix}Params");

	// Check if any param has a default value we can generate code for
	let has_defaults = params.iter().any(|p| {
		p.default_value_raw.is_some()
			&& default_value_expr(
				&resolve_param_type(p, enum_map),
				p.default_value_raw.as_ref().unwrap(),
				p,
				enum_map,
			)
			.is_some()
	});

	if has_defaults {
		writeln!(out, "#[derive(Debug, Clone, Serialize)]").unwrap();
	} else {
		writeln!(out, "#[derive(Debug, Clone, Default, Serialize)]").unwrap();
	}
	writeln!(out, "pub struct {struct_name} {{").unwrap();

	for param in params {
		let field_name = &param.name;
		let serde_name = &param.api_name;

		if let Some(ref default) = param.default_value {
			writeln!(out, "\t/// Default: {default}").unwrap();
		}
		// All query params are wrapped in Option
		if field_name != serde_name && !serde_name.contains("r#") {
			writeln!(
				out,
				"\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
			)
			.unwrap();
		} else {
			writeln!(out, "\t#[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
		}

		let rust_type = optionalize(&resolve_param_type(param, enum_map));
		writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// Generate custom Default impl with schema defaults
	if has_defaults {
		writeln!(out, "impl Default for {struct_name} {{").unwrap();
		writeln!(out, "\tfn default() -> Self {{").unwrap();
		writeln!(out, "\t\tSelf {{").unwrap();
		for param in params {
			let field_name = &param.name;
			let resolved = resolve_param_type(param, enum_map);
			if let Some(ref raw) = param.default_value_raw {
				if let Some(expr) = default_value_expr(&resolved, raw, param, enum_map) {
					writeln!(out, "\t\t\t{field_name}: Some({expr}),").unwrap();
					continue;
				}
			}
			writeln!(out, "\t\t\t{field_name}: None,").unwrap();
		}
		writeln!(out, "\t\t}}").unwrap();
		writeln!(out, "\t}}").unwrap();
		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();
	}
}

/// Emit a body struct for request body parameters.
fn emit_body_struct(
	out: &mut String,
	prefix: &str,
	params: &[ParamDef],
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let struct_name = format!("{prefix}Body");

	// Collect default functions to emit after the struct
	let mut default_fns: Vec<(String, String, String)> = Vec::new(); // (fn_name, return_type, expr)

	// Skip Default derive if any required param uses an enum type
	let has_required_enum = params.iter().any(|p| {
		p.required && p.enum_values.is_some() && resolve_param_type(p, enum_map) != p.rust_type
	});
	if has_required_enum {
		writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
	} else {
		writeln!(
			out,
			"#[derive(Debug, Clone, Default, Serialize, Deserialize)]"
		)
		.unwrap();
	}
	writeln!(out, "pub struct {struct_name} {{").unwrap();

	for param in params {
		let field_name = &param.name;
		let serde_name = &param.api_name;

		if let Some(ref default) = param.default_value {
			writeln!(out, "\t/// Default: {default}").unwrap();
		}
		let resolved_type = resolve_param_type(param, enum_map);

		// Check if we can generate a serde default function for this field
		let serde_default_fn = param.default_value_raw.as_ref().and_then(|raw| {
			let expr = default_value_expr(&resolved_type, raw, param, enum_map)?;
			let fn_name = default_fn_name(&struct_name, field_name);
			let ret_type = if param.required {
				resolved_type.clone()
			} else {
				optionalize(&resolved_type)
			};
			let full_expr = if param.required {
				expr
			} else {
				format!("Some({expr})")
			};
			default_fns.push((fn_name.clone(), ret_type, full_expr));
			Some(fn_name)
		});

		if param.required {
			let mut serde_attrs = Vec::new();
			if field_name != serde_name {
				serde_attrs.push(format!("rename = \"{serde_name}\""));
			}
			if let Some(ref fn_name) = serde_default_fn {
				serde_attrs.push(format!("default = \"{fn_name}\""));
			}
			if !serde_attrs.is_empty() {
				writeln!(out, "\t#[serde({})]", serde_attrs.join(", ")).unwrap();
			}
			writeln!(out, "\tpub {field_name}: {resolved_type},").unwrap();
		} else {
			let mut serde_attrs = Vec::new();
			if field_name != serde_name {
				serde_attrs.push(format!("rename = \"{serde_name}\""));
			}
			serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
			if let Some(ref fn_name) = serde_default_fn {
				serde_attrs.push(format!("default = \"{fn_name}\""));
			}
			writeln!(out, "\t#[serde({})]", serde_attrs.join(", ")).unwrap();
			let rust_type = optionalize(&resolved_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// Emit default functions
	for (fn_name, ret_type, expr) in &default_fns {
		writeln!(out, "fn {fn_name}() -> {ret_type} {{").unwrap();
		writeln!(out, "\t{expr}").unwrap();
		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();
	}
}

/// Emit a discriminated union enum for oneOf request bodies.
fn emit_one_of_body_enum(
	out: &mut String,
	prefix: &str,
	one_of: &OneOfBody,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let type_name = format!("{prefix}Body");
	let is_string_discriminator = one_of
		.variants
		.first()
		.is_some_and(|v| matches!(v.discriminator_value, OneOfDiscriminatorValue::String(_)));

	writeln!(out, "#[derive(Debug, Clone, Serialize)]").unwrap();
	if is_string_discriminator {
		writeln!(out, "#[serde(tag = \"{}\")]", one_of.discriminator_field).unwrap();
	} else {
		// Integer discriminators don't work with serde's internally tagged repr
		writeln!(out, "#[serde(untagged)]").unwrap();
	}
	writeln!(out, "pub enum {type_name} {{").unwrap();

	for variant in &one_of.variants {
		match &variant.discriminator_value {
			OneOfDiscriminatorValue::String(s) => {
				writeln!(out, "\t#[serde(rename = \"{s}\")]").unwrap();
			}
			OneOfDiscriminatorValue::Integer(_) => {
				// No rename attr for untagged — discriminator field is inside the struct
			}
		}
		write!(out, "\t{} {{", variant.variant_name).unwrap();

		// For integer discriminators, include the discriminator field in each variant
		if let OneOfDiscriminatorValue::Integer(n) = &variant.discriminator_value {
			writeln!(out).unwrap();
			writeln!(
				out,
				"\t\t/// Must be `{n}`. Set automatically by this variant."
			)
			.unwrap();
			writeln!(out, "\t\t{}: i64,", one_of.discriminator_field).unwrap();
		}

		if variant.params.is_empty() && is_string_discriminator {
			writeln!(out, " }},").unwrap();
		} else {
			if is_string_discriminator {
				writeln!(out).unwrap();
			}
			for param in &variant.params {
				let field_name = &param.name;
				let serde_name = &param.api_name;
				let resolved_type = resolve_param_type(param, enum_map);

				if param.required {
					if field_name != serde_name {
						writeln!(out, "\t\t#[serde(rename = \"{serde_name}\")]").unwrap();
					}
					writeln!(out, "\t\t{field_name}: {resolved_type},").unwrap();
				} else {
					if field_name != serde_name {
						writeln!(
							out,
							"\t\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
						)
						.unwrap();
					} else {
						writeln!(
							out,
							"\t\t#[serde(skip_serializing_if = \"Option::is_none\")]"
						)
						.unwrap();
					}
					let rust_type = optionalize(&resolved_type);
					writeln!(out, "\t\t{field_name}: {rust_type},").unwrap();
				}
			}
			writeln!(out, "\t}},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// For integer discriminators, emit constructors that set the discriminator automatically
	if !is_string_discriminator {
		writeln!(out, "impl {type_name} {{").unwrap();
		for variant in &one_of.variants {
			if let OneOfDiscriminatorValue::Integer(n) = &variant.discriminator_value {
				let fn_name = variant.variant_name.to_lowercase();
				write!(out, "\tpub fn {fn_name}(").unwrap();
				let mut first = true;
				for param in &variant.params {
					if !first {
						write!(out, ", ").unwrap();
					}
					first = false;
					let resolved_type = resolve_param_type(param, enum_map);
					let ty = if param.required {
						resolved_type
					} else {
						optionalize(&resolved_type)
					};
					write!(out, "{}: {ty}", param.name).unwrap();
				}
				writeln!(out, ") -> Self {{").unwrap();
				writeln!(out, "\t\tSelf::{} {{", variant.variant_name).unwrap();
				writeln!(out, "\t\t\t{}: {n},", one_of.discriminator_field).unwrap();
				for param in &variant.params {
					writeln!(out, "\t\t\t{},", param.name).unwrap();
				}
				writeln!(out, "\t\t}}").unwrap();
				writeln!(out, "\t}}").unwrap();
			}
		}
		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();
	}
}

/// Emit a body struct for multipart request body parameters.
/// Binary fields use `Vec<u8>`, no serde derives.
fn emit_multipart_body_struct(
	out: &mut String,
	prefix: &str,
	params: &[ParamDef],
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	writeln!(out, "#[derive(Debug, Clone)]").unwrap();
	writeln!(out, "pub struct {prefix}Body {{").unwrap();

	for param in params {
		let field_name = &param.name;
		if let Some(ref default) = param.default_value {
			writeln!(out, "\t/// Default: {default}").unwrap();
		}
		if param.is_binary {
			let rust_type = if param.required {
				"Vec<u8>".to_string()
			} else {
				"Option<Vec<u8>>".to_string()
			};
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		} else if param.required {
			let resolved_type = resolve_param_type(param, enum_map);
			writeln!(out, "\tpub {field_name}: {resolved_type},").unwrap();
		} else {
			let resolved_type = resolve_param_type(param, enum_map);
			let rust_type = optionalize(&resolved_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit a response type — either a struct or a type alias.
fn emit_response_type(out: &mut String, prefix: &str, schema: &ResponseSchema) {
	match schema {
		ResponseSchema::Alias(ty) => {
			writeln!(out, "pub type {prefix}Response = {ty};").unwrap();
			writeln!(out).unwrap();
		}
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => {
			// Emit nested structs first (dependencies before the parent)
			for (struct_name, nested_fields) in nested_structs {
				emit_response_struct(out, struct_name, nested_fields);
			}
			// Emit the top-level response struct
			emit_response_struct(out, &format!("{prefix}Response"), fields);
		}
	}
}

/// Emit a single response struct with Deserialize derive.
fn emit_response_struct(out: &mut String, struct_name: &str, fields: &[ResponseFieldDef]) {
	writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
	writeln!(out, "pub struct {struct_name} {{").unwrap();

	for field in fields {
		let field_name = &field.name;
		let api_name = &field.api_name;
		let needs_rename =
			field_name != api_name || api_name.contains('-') || field_name.starts_with("r#");

		if field.required {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{api_name}\")]").unwrap();
			}
			writeln!(out, "\tpub {field_name}: {},", field.rust_type).unwrap();
		} else {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{api_name}\", default)]").unwrap();
			} else {
				writeln!(out, "\t#[serde(default)]").unwrap();
			}
			let rust_type = optionalize(&field.rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit all group structs + impl blocks into the shared buffer (used by emit_client).
fn emit_groups_into(
	parsed: &ParseResult,
	out: &mut String,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	for group in &parsed.groups {
		let struct_name = &group.class_name;

		// Struct definition
		writeln!(out, "pub struct {struct_name} {{").unwrap();
		writeln!(out, "\thttp: Arc<HttpClient>,").unwrap();
		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();

		// Impl block
		writeln!(out, "impl {struct_name} {{").unwrap();
		writeln!(out, "\tpub(crate) fn new(http: Arc<HttpClient>) -> Self {{").unwrap();
		writeln!(out, "\t\tSelf {{ http }}").unwrap();
		writeln!(out, "\t}}").unwrap();

		let is_search_group = group.name == "category";
		for method in &group.methods {
			writeln!(out).unwrap();
			emit_method(out, &group.name, method, is_search_group, enum_map);
		}

		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();
	}
}

/// Emit a single method inside an impl block.
fn emit_method(
	out: &mut String,
	group_name: &str,
	method: &MethodDef,
	is_search: bool,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let prefix = method_type_prefix(group_name, &method.name);

	let required_query: Vec<_> = method.query_params.iter().filter(|p| p.required).collect();
	let optional_query: Vec<_> = method.query_params.iter().filter(|p| !p.required).collect();
	let has_optional_params = !optional_query.is_empty();

	// Doc comment
	if let Some(desc) = &method.description {
		writeln!(out, "\t/// {desc}").unwrap();
	}

	// Signature
	write!(out, "\tpub async fn {}(&self", method.name).unwrap();

	// Path params as direct arguments
	for param in &method.path_params {
		write!(out, ", {}: {}", param.name, param.rust_type).unwrap();
	}

	// Required query params as direct arguments
	for param in &required_query {
		let resolved_type = resolve_param_type(param, enum_map);
		write!(out, ", {}: {resolved_type}", param.name).unwrap();
	}

	// Optional query params struct
	if has_optional_params {
		write!(out, ", params: Option<&{prefix}Params>").unwrap();
	}

	// Body
	if method.is_raw_body {
		write!(out, ", body: serde_json::Value").unwrap();
	} else if method.has_body {
		write!(out, ", body: Option<&{prefix}Body>").unwrap();
	}

	if method.response_is_text {
		writeln!(out, ") -> Result<String, LolzteamError> {{").unwrap();
	} else {
		writeln!(out, ") -> Result<{prefix}Response, LolzteamError> {{").unwrap();
	}

	// Build path string
	let has_path_params = !method.path_params.is_empty();
	if has_path_params {
		// For raw identifiers (r#type), bind to a clean local variable first
		let has_raw_ident = method.path_params.iter().any(|p| p.name.starts_with("r#"));
		if has_raw_ident {
			for param in &method.path_params {
				if param.name.starts_with("r#") {
					let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
					// Use a prefixed local to avoid keyword conflict
					writeln!(out, "\t\tlet param_{clean} = {0};", param.name).unwrap();
				}
			}
		}
		let format_str = build_path_format_with_raw_prefix(&method.path, &method.path_params);
		writeln!(out, "\t\tlet path = format!(\"{format_str}\");").unwrap();
	}

	// Build query vec
	let has_any_query = !required_query.is_empty() || has_optional_params;
	if has_any_query {
		writeln!(out, "\t\tlet mut query = Vec::new();").unwrap();
		// Required query params — always pushed
		for param in &required_query {
			emit_required_query_push(out, param, "\t\t", enum_map);
		}
		// Optional query params — pushed from the params struct
		if has_optional_params {
			writeln!(out, "\t\tif let Some(p) = params {{").unwrap();
			for param in &optional_query {
				emit_param_push(out, "query", param, "\t\t\t", enum_map);
			}
			writeln!(out, "\t\t}}").unwrap();
		}
	}

	// Build body vec / parts depending on encoding
	let has_one_of = method.one_of_body.is_some();
	match method.body_encoding {
		BodyEncoding::Multipart if method.has_body && !method.is_raw_body => {
			writeln!(out, "\t\tlet mut parts = Vec::new();").unwrap();
			if let Some(ref one_of) = method.one_of_body {
				emit_one_of_multipart_match(out, &prefix, one_of, "\t\t");
			} else {
				writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
				for param in &method.body_params {
					emit_multipart_part_push(out, param, "\t\t\t", enum_map);
				}
				writeln!(out, "\t\t}}").unwrap();
			}
		}
		BodyEncoding::FormUrlEncoded if method.has_body && !method.is_raw_body && !has_one_of => {
			writeln!(out, "\t\tlet mut form = Vec::new();").unwrap();
			writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
			for param in &method.body_params {
				emit_param_push(out, "form", param, "\t\t\t", enum_map);
			}
			writeln!(out, "\t\t}}").unwrap();
		}
		BodyEncoding::Json if method.has_body && !method.is_raw_body => {
			// JSON body is passed directly as a serializable struct — no vec building needed
		}
		_ => {}
	}

	// Call self.http.request(...)
	let path_arg = if has_path_params {
		"&path"
	} else {
		&format!("\"{}\"", method.path)
	};

	let query_arg_some = "if query.is_empty() { None } else { Some(query.as_slice()) }";
	let is_search_arg = if is_search { "true" } else { "false" };

	if method.response_is_text {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		writeln!(
			out,
			"\t\tself.http.request_text(\"{}\", {path_arg}, {query_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.is_raw_body {
		// Raw JSON body (e.g. array-typed body like POST /batch)
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		writeln!(
			out,
			"\t\tself.http.request_json(\"{}\", {path_arg}, {query_arg}, Some(&body), {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.body_encoding == BodyEncoding::Multipart {
		writeln!(
			out,
			"\t\tself.http.request_multipart(\"{}\", {path_arg}, parts, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.body_encoding == BodyEncoding::Json {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		let body_arg = if method.has_body {
			"body"
		} else {
			"None::<&()>"
		};
		writeln!(
			out,
			"\t\tself.http.request_json(\"{}\", {path_arg}, {query_arg}, {body_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};

		let body_arg = if method.has_body {
			"if form.is_empty() { None } else { Some(form.as_slice()) }"
		} else {
			"None"
		};

		writeln!(
			out,
			"\t\tself.http.request(\"{}\", {path_arg}, {query_arg}, {body_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	}
	writeln!(out, "\t}}").unwrap();
}

/// Emit code to push a required query parameter (direct arg, not from struct) into the query vec.
fn emit_required_query_push(
	out: &mut String,
	param: &ParamDef,
	indent: &str,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let api_name = &param.api_name;
	let field = &param.name;
	let variant = &param.param_value_variant;

	let has_enum =
		param.enum_values.is_some() && resolve_param_type(param, enum_map) != param.rust_type;

	if has_enum {
		writeln!(
			out,
			"{indent}query.push((\"{api_name}\".into(), ParamValue::String({field}.to_string())));"
		)
		.unwrap();
		return;
	}

	let base_type = &param.rust_type;
	let is_string_or_int = base_type == "StringOrInt";

	if is_string_or_int {
		writeln!(out, "{indent}match &{field} {{").unwrap();
		writeln!(out, "{indent}\tStringOrInt::String(s) => query.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
		writeln!(out, "{indent}\tStringOrInt::Int(n) => query.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
		writeln!(out, "{indent}}}").unwrap();
	} else {
		let value_expr = match variant.as_str() {
			"String" => format!("ParamValue::String({field}.clone())"),
			"Integer" => format!("ParamValue::Integer({field})"),
			"Float" => format!("ParamValue::Float({field})"),
			"Bool" => format!("ParamValue::Bool({field})"),
			_ => format!("ParamValue::String({field}.to_string())"),
		};
		writeln!(
			out,
			"{indent}query.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
	}
}

/// Emit code to push a parameter value into a Vec.
fn emit_param_push(
	out: &mut String,
	vec_name: &str,
	param: &ParamDef,
	indent: &str,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let api_name = &param.api_name;
	let field = &param.name;
	let variant = &param.param_value_variant;

	// Determine the correct accessor based on whether we're in body or query context
	let accessor = if vec_name == "form" { "b" } else { "p" };

	let has_enum =
		param.enum_values.is_some() && resolve_param_type(param, enum_map) != param.rust_type;

	if has_enum {
		if param.required {
			writeln!(
				out,
				"{indent}{vec_name}.push((\"{api_name}\".into(), ParamValue::String({accessor}.{field}.to_string())));"
			)
			.unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
			writeln!(
				out,
				"{indent}\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(v.to_string())));"
			)
			.unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	let base_type = param
		.rust_type
		.strip_prefix("Option<")
		.and_then(|s| s.strip_suffix('>'))
		.unwrap_or(&param.rust_type);

	// deepObject params: HashMap<String, T> → loop with format!("{api_name}[{key}]")
	if param.is_deep_object {
		let value_expr = match variant.as_str() {
			"Integer" => "ParamValue::Integer(*val)",
			"Float" => "ParamValue::Float(*val)",
			"Bool" => "ParamValue::Bool(*val)",
			_ => "ParamValue::String(val.to_string())",
		};
		if param.required {
			writeln!(out, "{indent}for (key, val) in &{accessor}.{field} {{").unwrap();
			writeln!(
				out,
				"{indent}\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
			)
			.unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref map) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tfor (key, val) in map {{").unwrap();
			writeln!(
				out,
				"{indent}\t\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
			)
			.unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	let is_vec = base_type.starts_with("Vec<");

	if is_vec {
		// For Vec types, push each element as a separate param
		if param.required {
			writeln!(out, "{indent}for item in &{accessor}.{field} {{").unwrap();
			writeln!(
				out,
				"{indent}\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
			.unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tfor item in v {{").unwrap();
			writeln!(
				out,
				"{indent}\t\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
			.unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	// For serde_json::Value types, always use .to_string()
	let is_json_value = base_type == "serde_json::Value";
	let is_string_or_int = base_type == "StringOrInt";

	if is_string_or_int {
		// StringOrInt needs match arms for ParamValue conversion
		if param.required {
			writeln!(out, "{indent}match &{accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
			writeln!(out, "{indent}\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tmatch v {{").unwrap();
			writeln!(out, "{indent}\t\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
			writeln!(out, "{indent}\t\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	if param.required {
		let value_expr = if is_json_value {
			format!("ParamValue::String({accessor}.{field}.to_string())")
		} else {
			match variant.as_str() {
				"String" => format!("ParamValue::String({accessor}.{field}.clone())"),
				"Integer" => format!("ParamValue::Integer({accessor}.{field})"),
				"Float" => format!("ParamValue::Float({accessor}.{field})"),
				"Bool" => format!("ParamValue::Bool({accessor}.{field})"),
				_ => format!("ParamValue::String({accessor}.{field}.to_string())"),
			}
		};
		writeln!(
			out,
			"{indent}{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
	} else {
		writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
		let value_expr = if is_json_value {
			"ParamValue::String(v.to_string())".to_string()
		} else {
			match variant.as_str() {
				"String" => "ParamValue::String(v.clone())".to_string(),
				"Integer" => "ParamValue::Integer(*v)".to_string(),
				"Float" => "ParamValue::Float(*v)".to_string(),
				"Bool" => "ParamValue::Bool(*v)".to_string(),
				_ => "ParamValue::String(v.to_string())".to_string(),
			}
		};
		writeln!(
			out,
			"{indent}\t{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
		writeln!(out, "{indent}}}").unwrap();
	}
}

/// Emit code to push a multipart part into a Vec<MultipartPart>.
fn emit_multipart_part_push(
	out: &mut String,
	param: &ParamDef,
	indent: &str,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let api_name = &param.api_name;
	let field = &param.name;

	let has_enum =
		param.enum_values.is_some() && resolve_param_type(param, enum_map) != param.rust_type;

	if param.is_binary {
		// Binary field → MultipartPart::File
		if param.required {
			writeln!(out, "{indent}parts.push(MultipartPart::File {{").unwrap();
			writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\tdata: b.{field}.clone(),").unwrap();
			writeln!(out, "{indent}\tfilename: Some(\"{api_name}\".to_string()),").unwrap();
			writeln!(
				out,
				"{indent}\tmime_type: Some(\"application/octet-stream\".to_string()),"
			)
			.unwrap();
			writeln!(out, "{indent}}});").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
			writeln!(out, "{indent}\tparts.push(MultipartPart::File {{").unwrap();
			writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\t\tdata: v.clone(),").unwrap();
			writeln!(
				out,
				"{indent}\t\tfilename: Some(\"{api_name}\".to_string()),"
			)
			.unwrap();
			writeln!(
				out,
				"{indent}\t\tmime_type: Some(\"application/octet-stream\".to_string()),"
			)
			.unwrap();
			writeln!(out, "{indent}\t}});").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
	} else {
		// Text field → MultipartPart::Text
		let base_type = param
			.rust_type
			.strip_prefix("Option<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(&param.rust_type);
		let is_vec = base_type.starts_with("Vec<");

		if param.required {
			let value_expr = if is_vec {
				// Vec<String> → join with space (spaceDelimited encoding)
				format!("b.{field}.join(\" \")")
			} else if has_enum {
				format!("b.{field}.to_string()")
			} else {
				match param.param_value_variant.as_str() {
					"String" => format!("b.{field}.clone()"),
					_ => format!("b.{field}.to_string()"),
				}
			};
			writeln!(out, "{indent}parts.push(MultipartPart::Text {{").unwrap();
			writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\tvalue: {value_expr},").unwrap();
			writeln!(out, "{indent}}});").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
			let value_expr = if is_vec {
				"v.join(\" \")".to_string()
			} else if has_enum {
				"v.to_string()".to_string()
			} else {
				match param.param_value_variant.as_str() {
					"String" => "v.clone()".to_string(),
					_ => "v.to_string()".to_string(),
				}
			};
			writeln!(out, "{indent}\tparts.push(MultipartPart::Text {{").unwrap();
			writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\t\tvalue: {value_expr},").unwrap();
			writeln!(out, "{indent}\t}});").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
	}
}

/// Emit a match block that destructures a oneOf enum into multipart parts.
fn emit_one_of_multipart_match(out: &mut String, prefix: &str, one_of: &OneOfBody, indent: &str) {
	let type_name = format!("{prefix}Body");
	writeln!(out, "{indent}if let Some(b) = body {{").unwrap();
	writeln!(out, "{indent}\tmatch b {{").unwrap();
	for variant in &one_of.variants {
		// Build destructure pattern
		let field_names: Vec<&str> = variant.params.iter().map(|p| p.name.as_str()).collect();
		let disc_field = &one_of.discriminator_field;

		let has_disc_in_fields = matches!(
			variant.discriminator_value,
			OneOfDiscriminatorValue::Integer(_)
		);

		let mut pattern_fields = Vec::new();
		if has_disc_in_fields {
			pattern_fields.push(format!("{disc_field}: _"));
		}
		for name in &field_names {
			pattern_fields.push(name.to_string());
		}

		writeln!(
			out,
			"{indent}\t\t{type_name}::{} {{ {} }} => {{",
			variant.variant_name,
			pattern_fields.join(", ")
		)
		.unwrap();

		// Push discriminator field as a part
		match &variant.discriminator_value {
			OneOfDiscriminatorValue::String(s) => {
				writeln!(out, "{indent}\t\t\tparts.push(MultipartPart::Text {{").unwrap();
				writeln!(out, "{indent}\t\t\t\tname: \"{disc_field}\".to_string(),").unwrap();
				writeln!(out, "{indent}\t\t\t\tvalue: \"{s}\".to_string(),").unwrap();
				writeln!(out, "{indent}\t\t\t}});").unwrap();
			}
			OneOfDiscriminatorValue::Integer(n) => {
				writeln!(out, "{indent}\t\t\tparts.push(MultipartPart::Text {{").unwrap();
				writeln!(out, "{indent}\t\t\t\tname: \"{disc_field}\".to_string(),").unwrap();
				writeln!(out, "{indent}\t\t\t\tvalue: {n}.to_string(),").unwrap();
				writeln!(out, "{indent}\t\t\t}});").unwrap();
			}
		}

		// Push each variant's fields as parts
		for param in &variant.params {
			let field = &param.name;
			let api_name = &param.api_name;
			let is_vec = param.rust_type.starts_with("Vec<")
				|| param
					.rust_type
					.strip_prefix("Option<")
					.is_some_and(|s| s.starts_with("Vec<"));
			let base_is_vec = param
				.rust_type
				.strip_prefix("Option<")
				.and_then(|s| s.strip_suffix('>'))
				.unwrap_or(&param.rust_type)
				.starts_with("Vec<");

			if param.required {
				if base_is_vec {
					writeln!(out, "{indent}\t\t\tparts.push(MultipartPart::Text {{").unwrap();
					writeln!(out, "{indent}\t\t\t\tname: \"{api_name}\".to_string(),").unwrap();
					writeln!(
						out,
						"{indent}\t\t\t\tvalue: {field}.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(\" \"),"
					)
					.unwrap();
					writeln!(out, "{indent}\t\t\t}});").unwrap();
				} else {
					writeln!(out, "{indent}\t\t\tparts.push(MultipartPart::Text {{").unwrap();
					writeln!(out, "{indent}\t\t\t\tname: \"{api_name}\".to_string(),").unwrap();
					if param.rust_type == "String" {
						writeln!(out, "{indent}\t\t\t\tvalue: {field}.clone(),").unwrap();
					} else {
						writeln!(out, "{indent}\t\t\t\tvalue: {field}.to_string(),").unwrap();
					}
					writeln!(out, "{indent}\t\t\t}});").unwrap();
				}
			} else {
				writeln!(out, "{indent}\t\t\tif let Some(v) = {field} {{").unwrap();
				if is_vec || base_is_vec {
					writeln!(out, "{indent}\t\t\t\tparts.push(MultipartPart::Text {{").unwrap();
					writeln!(out, "{indent}\t\t\t\t\tname: \"{api_name}\".to_string(),").unwrap();
					writeln!(
						out,
						"{indent}\t\t\t\t\tvalue: v.iter().map(|i| i.to_string()).collect::<Vec<_>>().join(\" \"),"
					)
					.unwrap();
					writeln!(out, "{indent}\t\t\t\t}});").unwrap();
				} else {
					writeln!(out, "{indent}\t\t\t\tparts.push(MultipartPart::Text {{").unwrap();
					writeln!(out, "{indent}\t\t\t\t\tname: \"{api_name}\".to_string(),").unwrap();
					if param.rust_type.contains("String") {
						writeln!(out, "{indent}\t\t\t\t\tvalue: v.clone(),").unwrap();
					} else {
						writeln!(out, "{indent}\t\t\t\t\tvalue: v.to_string(),").unwrap();
					}
					writeln!(out, "{indent}\t\t\t\t}});").unwrap();
				}
				writeln!(out, "{indent}\t\t\t}}").unwrap();
			}
		}

		writeln!(out, "{indent}\t\t}}").unwrap();
	}
	writeln!(out, "{indent}\t}}").unwrap();
	writeln!(out, "{indent}}}").unwrap();
}

/// Emit the client file: all group structs + impl blocks + Client struct.
pub fn emit_client(
	parsed: &ParseResult,
	client_name: &str,
	default_base_url: &str,
	default_rate_limit: u32,
	default_search_rate_limit: Option<u32>,
	output_dir: &str,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(32768);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "use std::sync::Arc;").unwrap();
	writeln!(out).unwrap();

	// Compute union of imports across all groups
	let needs_multipart = parsed.groups.iter().any(|g| {
		g.methods
			.iter()
			.any(|m| m.body_encoding == BodyEncoding::Multipart && !m.is_raw_body)
	});
	let needs_pv = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			!m.query_params.is_empty()
				|| (m.has_body && !m.is_raw_body && m.body_encoding == BodyEncoding::FormUrlEncoded)
		})
	});
	let needs_string_or_int = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			let path_or_query = m.path_params.iter().chain(m.query_params.iter());
			let form_body = if !m.is_raw_body
				&& (m.body_encoding == BodyEncoding::FormUrlEncoded
					|| m.body_encoding == BodyEncoding::Multipart)
			{
				m.body_params.as_slice()
			} else {
				&[]
			};
			path_or_query
				.chain(form_body.iter())
				.any(|p| p.rust_type.contains("StringOrInt"))
		})
	});

	{
		let mut imports = vec![
			"ClientConfig",
			"HttpClient",
			"LolzteamError",
			"RateLimitConfig",
			"RetryConfig",
		];
		if needs_pv {
			imports.push("ParamValue");
		}
		if needs_multipart {
			imports.push("MultipartPart");
		}
		if needs_string_or_int {
			imports.push("StringOrInt");
		}
		imports.sort();
		let imports_str = imports.join(", ");
		writeln!(out, "use crate::runtime::{{{imports_str}}};").unwrap();
	}

	writeln!(out, "use super::types::*;").unwrap();
	writeln!(out).unwrap();

	// Emit all group structs + impl blocks
	emit_groups_into(parsed, &mut out, enum_map);

	// Struct
	writeln!(out, "pub struct {client_name} {{").unwrap();
	for group in &parsed.groups {
		writeln!(out, "\t{}: {},", group.name, group.class_name).unwrap();
	}
	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// Impl
	writeln!(out, "impl {client_name} {{").unwrap();

	// new(token)
	writeln!(out, "\t/// Create a new client with default configuration.").unwrap();
	writeln!(
		out,
		"\tpub fn new(token: impl Into<String>) -> Result<Self, LolzteamError> {{"
	)
	.unwrap();
	writeln!(out, "\t\tlet config = ClientConfig {{").unwrap();
	writeln!(out, "\t\t\ttoken: token.into(),").unwrap();
	writeln!(out, "\t\t\tbase_url: \"{default_base_url}\".to_string(),").unwrap();
	writeln!(out, "\t\t\tproxy: None,").unwrap();
	writeln!(out, "\t\t\tretry: Some(RetryConfig::default()),").unwrap();
	writeln!(
		out,
		"\t\t\trate_limit: Some(RateLimitConfig {{ requests_per_minute: {default_rate_limit} }}),"
	)
	.unwrap();
	match default_search_rate_limit {
		Some(srl) => {
			writeln!(
				out,
				"\t\t\tsearch_rate_limit: Some(RateLimitConfig {{ requests_per_minute: {srl} }}),"
			)
			.unwrap();
		}
		None => {
			writeln!(out, "\t\t\tsearch_rate_limit: None,").unwrap();
		}
	}
	writeln!(out, "\t\t\ttimeout_ms: Some(30_000),").unwrap();
	writeln!(out, "\t\t\ton_retry: None,").unwrap();
	writeln!(out, "\t\t}};").unwrap();
	writeln!(out, "\t\tSelf::with_config(config)").unwrap();
	writeln!(out, "\t}}").unwrap();
	writeln!(out).unwrap();

	// with_config(config)
	writeln!(out, "\t/// Create a new client with custom configuration.").unwrap();
	writeln!(
		out,
		"\tpub fn with_config(config: ClientConfig) -> Result<Self, LolzteamError> {{"
	)
	.unwrap();
	writeln!(out, "\t\tlet http = Arc::new(HttpClient::new(config)?);").unwrap();
	writeln!(out, "\t\tOk(Self {{").unwrap();
	for group in &parsed.groups {
		writeln!(
			out,
			"\t\t\t{}: {}::new(Arc::clone(&http)),",
			group.name, group.class_name
		)
		.unwrap();
	}
	writeln!(out, "\t\t}})").unwrap();
	writeln!(out, "\t}}").unwrap();

	// Accessor methods
	for group in &parsed.groups {
		writeln!(out).unwrap();
		writeln!(out, "\t/// Access the {} API group.", group.name).unwrap();
		writeln!(
			out,
			"\tpub fn {}(&self) -> &{} {{",
			group.name, group.class_name
		)
		.unwrap();
		writeln!(out, "\t\t&self.{}", group.name).unwrap();
		writeln!(out, "\t}}").unwrap();
	}

	writeln!(out, "}}").unwrap();

	let path = dir.join("client.rs");
	fs::write(&path, &out).expect("failed to write client.rs");
	eprintln!("  wrote {}", path.display());
}

/// Emit the mod.rs that re-exports everything.
pub fn emit_mod(_parsed: &ParseResult, output_dir: &str) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(256);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "mod client;").unwrap();
	writeln!(out, "mod types;").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "pub use client::*;").unwrap();
	writeln!(out, "pub use types::*;").unwrap();

	let path = dir.join("mod.rs");
	fs::write(&path, &out).expect("failed to write mod.rs");
	eprintln!("  wrote {}", path.display());
}

/// Emit the top-level generated/mod.rs
pub fn emit_generated_mod(output_dir: &str) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::new();
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "pub mod forum;").unwrap();
	writeln!(out, "pub mod market;").unwrap();

	let path = dir.join("mod.rs");
	fs::write(&path, &out).expect("failed to write generated/mod.rs");
	eprintln!("  wrote {}", path.display());
}

/// Build a Rust format! string from a path template.
/// to reference the local variable we bound above.
fn build_path_format_with_raw_prefix(path: &str, path_params: &[ParamDef]) -> String {
	let mut result = path.to_string();
	for param in path_params {
		let placeholder = format!("{{{}}}", param.api_name);
		let var_name = if param.name.starts_with("r#") {
			let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
			format!("param_{clean}")
		} else {
			param.name.clone()
		};
		let replacement = format!("{{{var_name}}}");
		result = result.replace(&placeholder, &replacement);
	}
	result
}

/// Generate a Rust expression for a default value, given the resolved type and raw JSON value.
///
/// Returns `None` if the value cannot be converted to a valid Rust expression.
fn default_value_expr(
	resolved_type: &str,
	raw: &Value,
	param: &ParamDef,
	enum_map: &BTreeMap<(String, EnumValues), EnumDef>,
) -> Option<String> {
	// If the field maps to an enum type, generate the correct variant constructor
	if let Some(ref ev) = param.enum_values {
		if let Some(type_name) = enums::lookup_enum_type(enum_map, &param.api_name, ev) {
			use heck::ToUpperCamelCase;
			return match raw {
				Value::String(s) => {
					let variant = s.to_upper_camel_case();
					Some(format!("{type_name}::{variant}"))
				}
				Value::Number(n) => {
					let val = n.as_i64()?;
					let variant = if val < 0 {
						format!("Neg{}", val.unsigned_abs())
					} else {
						format!("V{val}")
					};
					Some(format!("{type_name}::{variant}"))
				}
				_ => None,
			};
		}
	}

	// Plain types
	match raw {
		Value::String(s) => Some(format!("\"{s}\".to_string()")),
		Value::Number(n) => {
			if resolved_type.contains("f64") {
				Some(format!("{}_f64", n.as_f64()?))
			} else {
				Some(format!("{}_i64", n.as_i64()?))
			}
		}
		Value::Bool(b) => Some(format!("{b}")),
		_ => None,
	}
}

/// Generate a unique default function name for a struct field.
fn default_fn_name(struct_prefix: &str, field_name: &str) -> String {
	use heck::ToSnakeCase;
	format!("default_{}_{field_name}", struct_prefix.to_snake_case())
}

/// Wrap a type in Option if not already optional.
fn optionalize(rust_type: &str) -> String {
	if rust_type.starts_with("Option<") {
		rust_type.to_string()
	} else {
		format!("Option<{rust_type}>")
	}
}
