use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::parser::{MethodDef, ParamDef, ParseResult};
use crate::transforms::parameters::BodyEncoding;
use crate::transforms::responses::{
	component_ref_type, component_schema_to_rust_name, ResponseFieldDef, ResponseSchema,
};
use crate::transforms::types::schema_to_rust_type;
use crate::utils::deref;
use crate::utils::naming::{method_type_prefix, sanitize_ident};

/// Emit the types file (params, bodies, response aliases) for all groups.
pub fn emit_types(parsed: &ParseResult, root: &Value, output_dir: &str) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(8192);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();

	// Check if any type uses HashMap
	let needs_hashmap = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			m.query_params
				.iter()
				.chain(m.body_params.iter())
				.any(|p| p.rust_type.contains("HashMap"))
		})
	});
	if needs_hashmap {
		writeln!(out, "use std::collections::HashMap;").unwrap();
	}

	// Check if any type uses StringOrInt (in params, body, responses, or component schemas)
	let needs_string_or_int = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			let in_params = m
				.path_params
				.iter()
				.chain(m.query_params.iter())
				.chain(m.body_params.iter())
				.any(|p| p.rust_type.contains("StringOrInt"));
			let in_response = response_uses_string_or_int(&m.response_schema);
			in_params || in_response
		})
	}) || component_schemas_use_string_or_int(&parsed.component_schemas, root);
	if needs_string_or_int {
		writeln!(out, "use crate::runtime::StringOrInt;").unwrap();
	}

	writeln!(out).unwrap();

	// Emit component schemas (shared types referenced by multiple responses)
	let used_components = collect_used_component_schemas(parsed);
	if !used_components.is_empty() {
		writeln!(out, "// ── Component Schemas ──").unwrap();
		writeln!(out).unwrap();
		for name in &used_components {
			if let Some(schema) = parsed.component_schemas.get(name.as_str()) {
				emit_component_schema(&mut out, name, schema, root);
			}
		}
	}

	for group in &parsed.groups {
		for method in &group.methods {
			let prefix = method_type_prefix(&group.name, &method.name);

			// Params struct (only optional query parameters; required ones become direct args)
			let optional_query: Vec<_> = method
				.query_params
				.iter()
				.filter(|p| !p.required)
				.cloned()
				.collect();
			if !optional_query.is_empty() {
				emit_params_struct(&mut out, &prefix, &optional_query);
			}

			// Body struct (skip for raw body — those take serde_json::Value directly)
			if method.has_body && !method.is_raw_body {
				match method.body_encoding {
					BodyEncoding::Multipart => {
						emit_multipart_body_struct(&mut out, &prefix, &method.body_params);
					}
					_ => {
						emit_body_struct(&mut out, &prefix, &method.body_params);
					}
				}
			}

			// Response type
			emit_response_type(&mut out, &prefix, &method.response_schema);
		}
	}

	let path = dir.join("types.rs");
	fs::write(&path, &out).expect("failed to write types.rs");
	eprintln!("  wrote {}", path.display());
}

/// Check whether any response type references StringOrInt.
fn response_uses_string_or_int(schema: &ResponseSchema) -> bool {
	match schema {
		ResponseSchema::Alias(ty) => ty.contains("StringOrInt"),
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => {
			fields.iter().any(|f| f.rust_type.contains("StringOrInt"))
				|| nested_structs
					.iter()
					.any(|(_, fs)| fs.iter().any(|f| f.rust_type.contains("StringOrInt")))
		}
	}
}

/// Check whether any used component schema resolves to StringOrInt.
fn component_schemas_use_string_or_int(
	component_schemas: &BTreeMap<String, Value>,
	root: &Value,
) -> bool {
	component_schemas.values().any(|schema| {
		let (ty, _) = schema_to_rust_type(root, schema);
		ty.contains("StringOrInt")
	})
}

/// Collect the set of component schema original names that are actually referenced by response types.
/// Returns original schema names (e.g. `Resp_SystemInfo`), not Rust names.
fn collect_used_component_schemas(parsed: &ParseResult) -> Vec<String> {
	use std::collections::BTreeSet;

	// Build a reverse map: Rust name → original name
	let rust_to_original: BTreeMap<String, String> = parsed
		.component_schemas
		.keys()
		.map(|name| (component_schema_to_rust_name(name), name.clone()))
		.collect();

	let mut used_rust_names = BTreeSet::new();
	for group in &parsed.groups {
		for method in &group.methods {
			collect_component_refs_from_response(
				&method.response_schema,
				&rust_to_original,
				&mut used_rust_names,
			);
		}
	}

	// Map back to original names, preserving order
	used_rust_names
		.into_iter()
		.filter_map(|rust_name| rust_to_original.get(&rust_name).cloned())
		.collect()
}

/// Walk a ResponseSchema and collect Rust type names that match component schemas.
fn collect_component_refs_from_response(
	schema: &ResponseSchema,
	rust_to_original: &BTreeMap<String, String>,
	used: &mut std::collections::BTreeSet<String>,
) {
	let fields_iter: Box<dyn Iterator<Item = &ResponseFieldDef>> = match schema {
		ResponseSchema::Alias(_) => return,
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => Box::new(
			fields
				.iter()
				.chain(nested_structs.iter().flat_map(|(_, fs)| fs.iter())),
		),
	};
	for field in fields_iter {
		let ty = &field.rust_type;
		let inner = ty
			.strip_prefix("Vec<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(ty);
		let inner = inner
			.strip_prefix("Option<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(inner);
		if rust_to_original.contains_key(inner) {
			used.insert(inner.to_string());
		}
	}
}

/// Emit a component schema as a Rust type (struct, type alias, etc).
fn emit_component_schema(out: &mut String, name: &str, schema: &Value, root: &Value) {
	let rust_name = component_schema_to_rust_name(name);

	// Check for union types like ["string", "integer"] → use type alias to StringOrInt
	if let Some(type_arr) = schema.get("type").and_then(|v| v.as_array()) {
		let non_null: Vec<&str> = type_arr
			.iter()
			.filter_map(|v| v.as_str())
			.filter(|s| *s != "null")
			.collect();
		let mut sorted = non_null.clone();
		sorted.sort();
		if sorted == ["integer", "string"] {
			writeln!(out, "pub type {rust_name} = StringOrInt;").unwrap();
			writeln!(out).unwrap();
			return;
		}
		// Single primitive type
		if non_null.len() == 1 {
			let alias = match non_null[0] {
				"integer" => "i64",
				"string" => "String",
				"number" => "f64",
				"boolean" => "bool",
				_ => "serde_json::Value",
			};
			writeln!(out, "pub type {rust_name} = {alias};").unwrap();
			writeln!(out).unwrap();
			return;
		}
	}

	// Single type: integer → type alias
	if let Some(type_str) = schema.get("type").and_then(|v| v.as_str()) {
		match type_str {
			"integer" => {
				writeln!(out, "pub type {rust_name} = i64;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"string" => {
				writeln!(out, "pub type {rust_name} = String;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"number" => {
				writeln!(out, "pub type {rust_name} = f64;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"boolean" => {
				writeln!(out, "pub type {rust_name} = bool;").unwrap();
				writeln!(out).unwrap();
				return;
			}
			"object" => {
				// Fall through to struct generation below
			}
			_ => {
				writeln!(out, "pub type {rust_name} = serde_json::Value;").unwrap();
				writeln!(out).unwrap();
				return;
			}
		}
	}

	// Object with properties → generate struct
	let properties = match schema.get("properties").and_then(|v| v.as_object()) {
		Some(p) if !p.is_empty() => p,
		_ => {
			// Object without properties or no type
			writeln!(out, "pub type {rust_name} = serde_json::Value;").unwrap();
			writeln!(out).unwrap();
			return;
		}
	};

	let required_fields: Vec<String> = schema
		.get("required")
		.and_then(|v| v.as_array())
		.map(|arr| {
			arr.iter()
				.filter_map(|v| v.as_str().map(String::from))
				.collect()
		})
		.unwrap_or_default();

	writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
	writeln!(out, "pub struct {rust_name} {{").unwrap();

	for (prop_name, prop_schema) in properties {
		let field_name = sanitize_ident(prop_name);
		let required = required_fields.contains(prop_name);

		// Resolve type — check for nested $ref first
		let rust_type = if let Some(comp_type) = component_ref_type(prop_schema) {
			comp_type
		} else {
			let resolved = deref::deref(root, prop_schema);
			let (ty, _) = schema_to_rust_type(root, resolved);
			ty
		};

		let needs_rename =
			field_name != *prop_name || prop_name.contains('-') || field_name.starts_with("r#");

		if required {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{prop_name}\")]").unwrap();
			}
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		} else {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{prop_name}\", default)]").unwrap();
			} else {
				writeln!(out, "\t#[serde(default)]").unwrap();
			}
			let rust_type = optionalize(&rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit a params struct for query parameters.
fn emit_params_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
	writeln!(out, "#[derive(Debug, Clone, Default, Serialize)]").unwrap();
	writeln!(out, "pub struct {prefix}Params {{").unwrap();

	for param in params {
		let field_name = &param.name;
		let serde_name = &param.api_name;

		// All query params are wrapped in Option
		if field_name != serde_name && !serde_name.contains("r#") {
			writeln!(
				out,
				"\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
			)
			.unwrap();
		} else {
			writeln!(out, "\t#[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
		}

		let rust_type = optionalize(&param.rust_type);
		writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit a body struct for request body parameters.
fn emit_body_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
	writeln!(out, "#[derive(Debug, Clone, Default, Serialize)]").unwrap();
	writeln!(out, "pub struct {prefix}Body {{").unwrap();

	for param in params {
		let field_name = &param.name;
		let serde_name = &param.api_name;

		if param.required {
			if field_name != serde_name {
				writeln!(out, "\t#[serde(rename = \"{serde_name}\")]").unwrap();
			}
			writeln!(out, "\tpub {field_name}: {},", param.rust_type).unwrap();
		} else {
			if field_name != serde_name {
				writeln!(
					out,
					"\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
				)
				.unwrap();
			} else {
				writeln!(out, "\t#[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
			}
			let rust_type = optionalize(&param.rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit a body struct for multipart request body parameters.
/// Binary fields use `Vec<u8>`, no serde derives.
fn emit_multipart_body_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
	writeln!(out, "#[derive(Debug, Clone)]").unwrap();
	writeln!(out, "pub struct {prefix}Body {{").unwrap();

	for param in params {
		let field_name = &param.name;
		if param.is_binary {
			let rust_type = if param.required {
				"Vec<u8>".to_string()
			} else {
				"Option<Vec<u8>>".to_string()
			};
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		} else if param.required {
			writeln!(out, "\tpub {field_name}: {},", param.rust_type).unwrap();
		} else {
			let rust_type = optionalize(&param.rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit a response type — either a struct or a type alias.
fn emit_response_type(out: &mut String, prefix: &str, schema: &ResponseSchema) {
	match schema {
		ResponseSchema::Alias(ty) => {
			writeln!(out, "pub type {prefix}Response = {ty};").unwrap();
			writeln!(out).unwrap();
		}
		ResponseSchema::Struct {
			fields,
			nested_structs,
		} => {
			// Emit nested structs first (dependencies before the parent)
			for (struct_name, nested_fields) in nested_structs {
				emit_response_struct(out, struct_name, nested_fields);
			}
			// Emit the top-level response struct
			emit_response_struct(out, &format!("{prefix}Response"), fields);
		}
	}
}

/// Emit a single response struct with Deserialize derive.
fn emit_response_struct(out: &mut String, struct_name: &str, fields: &[ResponseFieldDef]) {
	writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
	writeln!(out, "pub struct {struct_name} {{").unwrap();

	for field in fields {
		let field_name = &field.name;
		let api_name = &field.api_name;
		let needs_rename =
			field_name != api_name || api_name.contains('-') || field_name.starts_with("r#");

		if field.required {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{api_name}\")]").unwrap();
			}
			writeln!(out, "\tpub {field_name}: {},", field.rust_type).unwrap();
		} else {
			if needs_rename {
				writeln!(out, "\t#[serde(rename = \"{api_name}\", default)]").unwrap();
			} else {
				writeln!(out, "\t#[serde(default)]").unwrap();
			}
			let rust_type = optionalize(&field.rust_type);
			writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
		}
	}

	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();
}

/// Emit all group structs + impl blocks into the shared buffer (used by emit_client).
fn emit_groups_into(parsed: &ParseResult, out: &mut String) {
	for group in &parsed.groups {
		let struct_name = &group.class_name;

		// Struct definition
		writeln!(out, "pub struct {struct_name} {{").unwrap();
		writeln!(out, "\thttp: Arc<HttpClient>,").unwrap();
		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();

		// Impl block
		writeln!(out, "impl {struct_name} {{").unwrap();
		writeln!(out, "\tpub(crate) fn new(http: Arc<HttpClient>) -> Self {{").unwrap();
		writeln!(out, "\t\tSelf {{ http }}").unwrap();
		writeln!(out, "\t}}").unwrap();

		let is_search_group = group.name == "category";
		for method in &group.methods {
			writeln!(out).unwrap();
			emit_method(out, &group.name, method, is_search_group);
		}

		writeln!(out, "}}").unwrap();
		writeln!(out).unwrap();
	}
}

/// Emit a single method inside an impl block.
fn emit_method(out: &mut String, group_name: &str, method: &MethodDef, is_search: bool) {
	let prefix = method_type_prefix(group_name, &method.name);

	let required_query: Vec<_> = method.query_params.iter().filter(|p| p.required).collect();
	let optional_query: Vec<_> = method.query_params.iter().filter(|p| !p.required).collect();
	let has_optional_params = !optional_query.is_empty();

	// Doc comment
	if let Some(desc) = &method.description {
		writeln!(out, "\t/// {desc}").unwrap();
	}

	// Signature
	write!(out, "\tpub async fn {}(&self", method.name).unwrap();

	// Path params as direct arguments
	for param in &method.path_params {
		write!(out, ", {}: {}", param.name, param.rust_type).unwrap();
	}

	// Required query params as direct arguments
	for param in &required_query {
		write!(out, ", {}: {}", param.name, param.rust_type).unwrap();
	}

	// Optional query params struct
	if has_optional_params {
		write!(out, ", params: Option<&{prefix}Params>").unwrap();
	}

	// Body
	if method.is_raw_body {
		write!(out, ", body: serde_json::Value").unwrap();
	} else if method.has_body {
		write!(out, ", body: Option<&{prefix}Body>").unwrap();
	}

	if method.response_is_text {
		writeln!(out, ") -> Result<String, LolzteamError> {{").unwrap();
	} else {
		writeln!(out, ") -> Result<{prefix}Response, LolzteamError> {{").unwrap();
	}

	// Build path string
	let has_path_params = !method.path_params.is_empty();
	if has_path_params {
		// For raw identifiers (r#type), bind to a clean local variable first
		let has_raw_ident = method.path_params.iter().any(|p| p.name.starts_with("r#"));
		if has_raw_ident {
			for param in &method.path_params {
				if param.name.starts_with("r#") {
					let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
					// Use a prefixed local to avoid keyword conflict
					writeln!(out, "\t\tlet param_{clean} = {0};", param.name).unwrap();
				}
			}
		}
		let format_str = build_path_format_with_raw_prefix(&method.path, &method.path_params);
		writeln!(out, "\t\tlet path = format!(\"{format_str}\");").unwrap();
	}

	// Build query vec
	let has_any_query = !required_query.is_empty() || has_optional_params;
	if has_any_query {
		writeln!(out, "\t\tlet mut query = Vec::new();").unwrap();
		// Required query params — always pushed
		for param in &required_query {
			emit_required_query_push(out, param, "\t\t");
		}
		// Optional query params — pushed from the params struct
		if has_optional_params {
			writeln!(out, "\t\tif let Some(p) = params {{").unwrap();
			for param in &optional_query {
				emit_param_push(out, "query", param, "\t\t\t");
			}
			writeln!(out, "\t\t}}").unwrap();
		}
	}

	// Build body vec / parts depending on encoding
	match method.body_encoding {
		BodyEncoding::Multipart if method.has_body && !method.is_raw_body => {
			writeln!(out, "\t\tlet mut parts = Vec::new();").unwrap();
			writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
			for param in &method.body_params {
				emit_multipart_part_push(out, param, "\t\t\t");
			}
			writeln!(out, "\t\t}}").unwrap();
		}
		BodyEncoding::FormUrlEncoded if method.has_body && !method.is_raw_body => {
			writeln!(out, "\t\tlet mut form = Vec::new();").unwrap();
			writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
			for param in &method.body_params {
				emit_param_push(out, "form", param, "\t\t\t");
			}
			writeln!(out, "\t\t}}").unwrap();
		}
		BodyEncoding::Json if method.has_body && !method.is_raw_body => {
			// JSON body is passed directly as a serializable struct — no vec building needed
		}
		_ => {}
	}

	// Call self.http.request(...)
	let path_arg = if has_path_params {
		"&path"
	} else {
		&format!("\"{}\"", method.path)
	};

	let query_arg_some = "if query.is_empty() { None } else { Some(query.as_slice()) }";
	let is_search_arg = if is_search { "true" } else { "false" };

	if method.response_is_text {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		writeln!(
			out,
			"\t\tself.http.request_text(\"{}\", {path_arg}, {query_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.is_raw_body {
		// Raw JSON body (e.g. array-typed body like POST /batch)
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		writeln!(
			out,
			"\t\tself.http.request_json(\"{}\", {path_arg}, {query_arg}, Some(&body), {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.body_encoding == BodyEncoding::Multipart {
		writeln!(
			out,
			"\t\tself.http.request_multipart(\"{}\", {path_arg}, parts, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else if method.body_encoding == BodyEncoding::Json {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};
		let body_arg = if method.has_body {
			"body"
		} else {
			"None::<&()>"
		};
		writeln!(
			out,
			"\t\tself.http.request_json(\"{}\", {path_arg}, {query_arg}, {body_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	} else {
		let query_arg = if has_any_query {
			query_arg_some
		} else {
			"None"
		};

		let body_arg = if method.has_body {
			"if form.is_empty() { None } else { Some(form.as_slice()) }"
		} else {
			"None"
		};

		writeln!(
			out,
			"\t\tself.http.request(\"{}\", {path_arg}, {query_arg}, {body_arg}, {is_search_arg}).await",
			method.http_method
		)
		.unwrap();
	}
	writeln!(out, "\t}}").unwrap();
}

/// Emit code to push a required query parameter (direct arg, not from struct) into the query vec.
fn emit_required_query_push(out: &mut String, param: &ParamDef, indent: &str) {
	let api_name = &param.api_name;
	let field = &param.name;
	let variant = &param.param_value_variant;

	let base_type = &param.rust_type;
	let is_string_or_int = base_type == "StringOrInt";

	if is_string_or_int {
		writeln!(out, "{indent}match &{field} {{").unwrap();
		writeln!(out, "{indent}\tStringOrInt::String(s) => query.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
		writeln!(out, "{indent}\tStringOrInt::Int(n) => query.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
		writeln!(out, "{indent}}}").unwrap();
	} else {
		let value_expr = match variant.as_str() {
			"String" => format!("ParamValue::String({field}.clone())"),
			"Integer" => format!("ParamValue::Integer({field})"),
			"Float" => format!("ParamValue::Float({field})"),
			"Bool" => format!("ParamValue::Bool({field})"),
			_ => format!("ParamValue::String({field}.to_string())"),
		};
		writeln!(
			out,
			"{indent}query.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
	}
}

/// Emit code to push a parameter value into a Vec.
fn emit_param_push(out: &mut String, vec_name: &str, param: &ParamDef, indent: &str) {
	let api_name = &param.api_name;
	let field = &param.name;
	let variant = &param.param_value_variant;

	// Determine the correct accessor based on whether we're in body or query context
	let accessor = if vec_name == "form" { "b" } else { "p" };

	let base_type = param
		.rust_type
		.strip_prefix("Option<")
		.and_then(|s| s.strip_suffix('>'))
		.unwrap_or(&param.rust_type);

	// deepObject params: HashMap<String, T> → loop with format!("{api_name}[{key}]")
	if param.is_deep_object {
		let value_expr = match variant.as_str() {
			"Integer" => "ParamValue::Integer(*val)",
			"Float" => "ParamValue::Float(*val)",
			"Bool" => "ParamValue::Bool(*val)",
			_ => "ParamValue::String(val.to_string())",
		};
		if param.required {
			writeln!(out, "{indent}for (key, val) in &{accessor}.{field} {{").unwrap();
			writeln!(
				out,
				"{indent}\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
			)
			.unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref map) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tfor (key, val) in map {{").unwrap();
			writeln!(
				out,
				"{indent}\t\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
			)
			.unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	let is_vec = base_type.starts_with("Vec<");

	if is_vec {
		// For Vec types, push each element as a separate param
		if param.required {
			writeln!(out, "{indent}for item in &{accessor}.{field} {{").unwrap();
			writeln!(
				out,
				"{indent}\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
			.unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tfor item in v {{").unwrap();
			writeln!(
				out,
				"{indent}\t\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
			.unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	// For serde_json::Value types, always use .to_string()
	let is_json_value = base_type == "serde_json::Value";
	let is_string_or_int = base_type == "StringOrInt";

	if is_string_or_int {
		// StringOrInt needs match arms for ParamValue conversion
		if param.required {
			writeln!(out, "{indent}match &{accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
			writeln!(out, "{indent}\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
			writeln!(out, "{indent}\tmatch v {{").unwrap();
			writeln!(out, "{indent}\t\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
			writeln!(out, "{indent}\t\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
			writeln!(out, "{indent}\t}}").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
		return;
	}

	if param.required {
		let value_expr = if is_json_value {
			format!("ParamValue::String({accessor}.{field}.to_string())")
		} else {
			match variant.as_str() {
				"String" => format!("ParamValue::String({accessor}.{field}.clone())"),
				"Integer" => format!("ParamValue::Integer({accessor}.{field})"),
				"Float" => format!("ParamValue::Float({accessor}.{field})"),
				"Bool" => format!("ParamValue::Bool({accessor}.{field})"),
				_ => format!("ParamValue::String({accessor}.{field}.to_string())"),
			}
		};
		writeln!(
			out,
			"{indent}{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
	} else {
		writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
		let value_expr = if is_json_value {
			"ParamValue::String(v.to_string())".to_string()
		} else {
			match variant.as_str() {
				"String" => "ParamValue::String(v.clone())".to_string(),
				"Integer" => "ParamValue::Integer(*v)".to_string(),
				"Float" => "ParamValue::Float(*v)".to_string(),
				"Bool" => "ParamValue::Bool(*v)".to_string(),
				_ => "ParamValue::String(v.to_string())".to_string(),
			}
		};
		writeln!(
			out,
			"{indent}\t{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
		)
		.unwrap();
		writeln!(out, "{indent}}}").unwrap();
	}
}

/// Emit code to push a multipart part into a Vec<MultipartPart>.
fn emit_multipart_part_push(out: &mut String, param: &ParamDef, indent: &str) {
	let api_name = &param.api_name;
	let field = &param.name;

	if param.is_binary {
		// Binary field → MultipartPart::File
		if param.required {
			writeln!(out, "{indent}parts.push(MultipartPart::File {{").unwrap();
			writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\tdata: b.{field}.clone(),").unwrap();
			writeln!(out, "{indent}\tfilename: Some(\"{api_name}\".to_string()),").unwrap();
			writeln!(
				out,
				"{indent}\tmime_type: Some(\"application/octet-stream\".to_string()),"
			)
			.unwrap();
			writeln!(out, "{indent}}});").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
			writeln!(out, "{indent}\tparts.push(MultipartPart::File {{").unwrap();
			writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\t\tdata: v.clone(),").unwrap();
			writeln!(
				out,
				"{indent}\t\tfilename: Some(\"{api_name}\".to_string()),"
			)
			.unwrap();
			writeln!(
				out,
				"{indent}\t\tmime_type: Some(\"application/octet-stream\".to_string()),"
			)
			.unwrap();
			writeln!(out, "{indent}\t}});").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
	} else {
		// Text field → MultipartPart::Text
		let base_type = param
			.rust_type
			.strip_prefix("Option<")
			.and_then(|s| s.strip_suffix('>'))
			.unwrap_or(&param.rust_type);
		let is_vec = base_type.starts_with("Vec<");

		if param.required {
			let value_expr = if is_vec {
				// Vec<String> → join with space (spaceDelimited encoding)
				format!("b.{field}.join(\" \")")
			} else {
				match param.param_value_variant.as_str() {
					"String" => format!("b.{field}.clone()"),
					_ => format!("b.{field}.to_string()"),
				}
			};
			writeln!(out, "{indent}parts.push(MultipartPart::Text {{").unwrap();
			writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\tvalue: {value_expr},").unwrap();
			writeln!(out, "{indent}}});").unwrap();
		} else {
			writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
			let value_expr = if is_vec {
				"v.join(\" \")".to_string()
			} else {
				match param.param_value_variant.as_str() {
					"String" => "v.clone()".to_string(),
					_ => "v.to_string()".to_string(),
				}
			};
			writeln!(out, "{indent}\tparts.push(MultipartPart::Text {{").unwrap();
			writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
			writeln!(out, "{indent}\t\tvalue: {value_expr},").unwrap();
			writeln!(out, "{indent}\t}});").unwrap();
			writeln!(out, "{indent}}}").unwrap();
		}
	}
}

/// Emit the client file: all group structs + impl blocks + Client struct.
pub fn emit_client(
	parsed: &ParseResult,
	client_name: &str,
	default_base_url: &str,
	default_rate_limit: u32,
	default_search_rate_limit: Option<u32>,
	output_dir: &str,
) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(32768);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "use std::sync::Arc;").unwrap();
	writeln!(out).unwrap();

	// Compute union of imports across all groups
	let needs_multipart = parsed.groups.iter().any(|g| {
		g.methods
			.iter()
			.any(|m| m.body_encoding == BodyEncoding::Multipart && !m.is_raw_body)
	});
	let needs_pv = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			!m.query_params.is_empty()
				|| (m.has_body && !m.is_raw_body && m.body_encoding == BodyEncoding::FormUrlEncoded)
		})
	});
	let needs_string_or_int = parsed.groups.iter().any(|g| {
		g.methods.iter().any(|m| {
			let path_or_query = m.path_params.iter().chain(m.query_params.iter());
			let form_body = if !m.is_raw_body
				&& (m.body_encoding == BodyEncoding::FormUrlEncoded
					|| m.body_encoding == BodyEncoding::Multipart)
			{
				m.body_params.as_slice()
			} else {
				&[]
			};
			path_or_query
				.chain(form_body.iter())
				.any(|p| p.rust_type.contains("StringOrInt"))
		})
	});

	{
		let mut imports = vec![
			"ClientConfig",
			"HttpClient",
			"LolzteamError",
			"RateLimitConfig",
			"RetryConfig",
		];
		if needs_pv {
			imports.push("ParamValue");
		}
		if needs_multipart {
			imports.push("MultipartPart");
		}
		if needs_string_or_int {
			imports.push("StringOrInt");
		}
		imports.sort();
		let imports_str = imports.join(", ");
		writeln!(out, "use crate::runtime::{{{imports_str}}};").unwrap();
	}

	writeln!(out, "use super::types::*;").unwrap();
	writeln!(out).unwrap();

	// Emit all group structs + impl blocks
	emit_groups_into(parsed, &mut out);

	// Struct
	writeln!(out, "pub struct {client_name} {{").unwrap();
	for group in &parsed.groups {
		writeln!(out, "\t{}: {},", group.name, group.class_name).unwrap();
	}
	writeln!(out, "}}").unwrap();
	writeln!(out).unwrap();

	// Impl
	writeln!(out, "impl {client_name} {{").unwrap();

	// new(token)
	writeln!(out, "\t/// Create a new client with default configuration.").unwrap();
	writeln!(
		out,
		"\tpub fn new(token: impl Into<String>) -> Result<Self, LolzteamError> {{"
	)
	.unwrap();
	writeln!(out, "\t\tlet config = ClientConfig {{").unwrap();
	writeln!(out, "\t\t\ttoken: token.into(),").unwrap();
	writeln!(out, "\t\t\tbase_url: \"{default_base_url}\".to_string(),").unwrap();
	writeln!(out, "\t\t\tproxy: None,").unwrap();
	writeln!(out, "\t\t\tretry: Some(RetryConfig::default()),").unwrap();
	writeln!(
		out,
		"\t\t\trate_limit: Some(RateLimitConfig {{ requests_per_minute: {default_rate_limit} }}),"
	)
	.unwrap();
	match default_search_rate_limit {
		Some(srl) => {
			writeln!(
				out,
				"\t\t\tsearch_rate_limit: Some(RateLimitConfig {{ requests_per_minute: {srl} }}),"
			)
			.unwrap();
		}
		None => {
			writeln!(out, "\t\t\tsearch_rate_limit: None,").unwrap();
		}
	}
	writeln!(out, "\t\t\ttimeout_ms: None,").unwrap();
	writeln!(out, "\t\t\ton_retry: None,").unwrap();
	writeln!(out, "\t\t}};").unwrap();
	writeln!(out, "\t\tSelf::with_config(config)").unwrap();
	writeln!(out, "\t}}").unwrap();
	writeln!(out).unwrap();

	// with_config(config)
	writeln!(out, "\t/// Create a new client with custom configuration.").unwrap();
	writeln!(
		out,
		"\tpub fn with_config(config: ClientConfig) -> Result<Self, LolzteamError> {{"
	)
	.unwrap();
	writeln!(out, "\t\tlet http = Arc::new(HttpClient::new(config)?);").unwrap();
	writeln!(out, "\t\tOk(Self {{").unwrap();
	for group in &parsed.groups {
		writeln!(
			out,
			"\t\t\t{}: {}::new(Arc::clone(&http)),",
			group.name, group.class_name
		)
		.unwrap();
	}
	writeln!(out, "\t\t}})").unwrap();
	writeln!(out, "\t}}").unwrap();

	// Accessor methods
	for group in &parsed.groups {
		writeln!(out).unwrap();
		writeln!(out, "\t/// Access the {} API group.", group.name).unwrap();
		writeln!(
			out,
			"\tpub fn {}(&self) -> &{} {{",
			group.name, group.class_name
		)
		.unwrap();
		writeln!(out, "\t\t&self.{}", group.name).unwrap();
		writeln!(out, "\t}}").unwrap();
	}

	writeln!(out, "}}").unwrap();

	let path = dir.join("client.rs");
	fs::write(&path, &out).expect("failed to write client.rs");
	eprintln!("  wrote {}", path.display());
}

/// Emit the mod.rs that re-exports everything.
pub fn emit_mod(_parsed: &ParseResult, output_dir: &str) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::with_capacity(256);
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "mod client;").unwrap();
	writeln!(out, "mod types;").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "pub use client::*;").unwrap();
	writeln!(out, "pub use types::*;").unwrap();

	let path = dir.join("mod.rs");
	fs::write(&path, &out).expect("failed to write mod.rs");
	eprintln!("  wrote {}", path.display());
}

/// Emit the top-level generated/mod.rs
pub fn emit_generated_mod(output_dir: &str) {
	let dir = Path::new(output_dir);
	fs::create_dir_all(dir).expect("failed to create output directory");

	let mut out = String::new();
	writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
	writeln!(out).unwrap();
	writeln!(out, "pub mod forum;").unwrap();
	writeln!(out, "pub mod market;").unwrap();

	let path = dir.join("mod.rs");
	fs::write(&path, &out).expect("failed to write generated/mod.rs");
	eprintln!("  wrote {}", path.display());
}

/// Build a Rust format! string from a path template.
/// to reference the local variable we bound above.
fn build_path_format_with_raw_prefix(path: &str, path_params: &[ParamDef]) -> String {
	let mut result = path.to_string();
	for param in path_params {
		let placeholder = format!("{{{}}}", param.api_name);
		let var_name = if param.name.starts_with("r#") {
			let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
			format!("param_{clean}")
		} else {
			param.name.clone()
		};
		let replacement = format!("{{{var_name}}}");
		result = result.replace(&placeholder, &replacement);
	}
	result
}

/// Wrap a type in Option if not already optional.
fn optionalize(rust_type: &str) -> String {
	if rust_type.starts_with("Option<") {
		rust_type.to_string()
	} else {
		format!("Option<{rust_type}>")
	}
}
