use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::parser::{MethodDef, ParamDef, ParseResult};
use crate::transforms::parameters::BodyEncoding;
use crate::transforms::responses::{ResponseFieldDef, ResponseSchema};
use crate::utils::naming::method_type_prefix;

/// Emit the types file (params, bodies, response aliases) for all groups.
pub fn emit_types(parsed: &ParseResult, output_dir: &str) {
    let dir = Path::new(output_dir);
    fs::create_dir_all(dir).expect("failed to create output directory");

    let mut out = String::with_capacity(8192);
    writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();

    // Check if any type uses HashMap
    let needs_hashmap = parsed.groups.iter().any(|g| {
        g.methods.iter().any(|m| {
            m.query_params
                .iter()
                .chain(m.body_params.iter())
                .any(|p| p.rust_type.contains("HashMap"))
        })
    });
    if needs_hashmap {
        writeln!(out, "use std::collections::HashMap;").unwrap();
    }

    // Check if any type uses StringOrInt
    let needs_string_or_int = parsed.groups.iter().any(|g| {
        g.methods.iter().any(|m| {
            m.path_params
                .iter()
                .chain(m.query_params.iter())
                .chain(m.body_params.iter())
                .any(|p| p.rust_type.contains("StringOrInt"))
        })
    });
    if needs_string_or_int {
        writeln!(out, "use crate::runtime::StringOrInt;").unwrap();
    }

    writeln!(out).unwrap();

    for group in &parsed.groups {
        for method in &group.methods {
            let prefix = method_type_prefix(&group.name, &method.name);

            // Params struct (query parameters)
            if method.has_params {
                emit_params_struct(&mut out, &prefix, &method.query_params);
            }

            // Body struct
            if method.has_body {
                match method.body_encoding {
                    BodyEncoding::Multipart => {
                        emit_multipart_body_struct(&mut out, &prefix, &method.body_params);
                    }
                    _ => {
                        emit_body_struct(&mut out, &prefix, &method.body_params);
                    }
                }
            }

            // Response type
            emit_response_type(&mut out, &prefix, &method.response_schema);
        }
    }

    let path = dir.join("types.rs");
    fs::write(&path, &out).expect("failed to write types.rs");
    eprintln!("  wrote {}", path.display());
}

/// Emit a params struct for query parameters.
fn emit_params_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
    writeln!(out, "#[derive(Debug, Clone, Default, Serialize)]").unwrap();
    writeln!(out, "pub struct {prefix}Params {{").unwrap();

    for param in params {
        let field_name = &param.name;
        let serde_name = &param.api_name;

        // All query params are wrapped in Option
        if field_name != serde_name && !serde_name.contains("r#") {
            writeln!(
                out,
                "\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
            )
            .unwrap();
        } else {
            writeln!(out, "\t#[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
        }

        let rust_type = optionalize(&param.rust_type);
        writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit a body struct for request body parameters.
fn emit_body_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
    writeln!(out, "#[derive(Debug, Clone, Default, Serialize)]").unwrap();
    writeln!(out, "pub struct {prefix}Body {{").unwrap();

    for param in params {
        let field_name = &param.name;
        let serde_name = &param.api_name;

        if param.required {
            if field_name != serde_name {
                writeln!(out, "\t#[serde(rename = \"{serde_name}\")]").unwrap();
            }
            writeln!(out, "\tpub {field_name}: {},", param.rust_type).unwrap();
        } else {
            if field_name != serde_name {
                writeln!(
					out,
					"\t#[serde(rename = \"{serde_name}\", skip_serializing_if = \"Option::is_none\")]"
				)
                .unwrap();
            } else {
                writeln!(out, "\t#[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
            }
            let rust_type = optionalize(&param.rust_type);
            writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit a body struct for multipart request body parameters.
/// Binary fields use `Vec<u8>`, no serde derives.
fn emit_multipart_body_struct(out: &mut String, prefix: &str, params: &[ParamDef]) {
    writeln!(out, "#[derive(Debug, Clone)]").unwrap();
    writeln!(out, "pub struct {prefix}Body {{").unwrap();

    for param in params {
        let field_name = &param.name;
        if param.is_binary {
            let rust_type = if param.required {
                "Vec<u8>".to_string()
            } else {
                "Option<Vec<u8>>".to_string()
            };
            writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
        } else if param.required {
            writeln!(out, "\tpub {field_name}: {},", param.rust_type).unwrap();
        } else {
            let rust_type = optionalize(&param.rust_type);
            writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit a response type — either a struct or a type alias.
fn emit_response_type(out: &mut String, prefix: &str, schema: &ResponseSchema) {
    match schema {
        ResponseSchema::Alias(ty) => {
            writeln!(out, "pub type {prefix}Response = {ty};").unwrap();
            writeln!(out).unwrap();
        }
        ResponseSchema::Struct {
            fields,
            nested_structs,
        } => {
            // Emit nested structs first (dependencies before the parent)
            for (struct_name, nested_fields) in nested_structs {
                emit_response_struct(out, struct_name, nested_fields);
            }
            // Emit the top-level response struct
            emit_response_struct(out, &format!("{prefix}Response"), fields);
        }
    }
}

/// Emit a single response struct with Deserialize derive.
fn emit_response_struct(out: &mut String, struct_name: &str, fields: &[ResponseFieldDef]) {
    writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();

    for field in fields {
        let field_name = &field.name;
        let api_name = &field.api_name;
        let needs_rename =
            field_name != api_name || api_name.contains('-') || field_name.starts_with("r#");

        if field.required {
            if needs_rename {
                writeln!(out, "\t#[serde(rename = \"{api_name}\")]").unwrap();
            }
            writeln!(out, "\tpub {field_name}: {},", field.rust_type).unwrap();
        } else {
            if needs_rename {
                writeln!(out, "\t#[serde(rename = \"{api_name}\", default)]").unwrap();
            } else {
                writeln!(out, "\t#[serde(default)]").unwrap();
            }
            let rust_type = optionalize(&field.rust_type);
            writeln!(out, "\tpub {field_name}: {rust_type},").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit per-group API struct files.
pub fn emit_groups(parsed: &ParseResult, output_dir: &str) {
    let dir = Path::new(output_dir);
    fs::create_dir_all(dir).expect("failed to create output directory");

    for group in &parsed.groups {
        let mut out = String::with_capacity(4096);
        writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "use std::sync::Arc;").unwrap();
        writeln!(out).unwrap();

        let needs_multipart = group
            .methods
            .iter()
            .any(|m| m.body_encoding == BodyEncoding::Multipart);

        // ParamValue needed for: query params (any method) or form-urlencoded body params
        let needs_pv = group.methods.iter().any(|m| {
            m.has_params || (m.has_body && m.body_encoding == BodyEncoding::FormUrlEncoded)
        });

        let needs_string_or_int = group.methods.iter().any(|m| {
            // StringOrInt needed in runtime import only for path params and form-encoded/multipart body params
            // JSON body params don't need it (struct is serialized directly via serde)
            let path_or_query = m.path_params.iter().chain(m.query_params.iter());
            let form_body = if m.body_encoding == BodyEncoding::FormUrlEncoded
                || m.body_encoding == BodyEncoding::Multipart
            {
                m.body_params.as_slice()
            } else {
                &[]
            };
            path_or_query
                .chain(form_body.iter())
                .any(|p| p.rust_type.contains("StringOrInt"))
        });

        {
            let mut imports = vec!["HttpClient", "LolzteamError"];
            if needs_pv {
                imports.push("ParamValue");
            }
            if needs_multipart {
                imports.push("MultipartPart");
            }
            if needs_string_or_int {
                imports.push("StringOrInt");
            }
            let imports_str = imports.join(", ");
            writeln!(out, "use crate::runtime::{{{imports_str}}};").unwrap();
        }

        writeln!(out, "use super::types::*;").unwrap();
        writeln!(out).unwrap();

        let struct_name = &group.class_name;

        // Struct definition
        writeln!(out, "pub struct {struct_name} {{").unwrap();
        writeln!(out, "\thttp: Arc<HttpClient>,").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Impl block
        writeln!(out, "impl {struct_name} {{").unwrap();
        writeln!(out, "\tpub(crate) fn new(http: Arc<HttpClient>) -> Self {{").unwrap();
        writeln!(out, "\t\tSelf {{ http }}").unwrap();
        writeln!(out, "\t}}").unwrap();

        for method in &group.methods {
            writeln!(out).unwrap();
            emit_method(&mut out, &group.name, method);
        }

        writeln!(out, "}}").unwrap();

        let path = dir.join(format!("{}.rs", group.file_name));
        fs::write(&path, &out).expect("failed to write group file");
        eprintln!("  wrote {}", path.display());
    }
}

/// Emit a single method inside an impl block.
fn emit_method(out: &mut String, group_name: &str, method: &MethodDef) {
    let prefix = method_type_prefix(group_name, &method.name);

    // Doc comment
    if let Some(desc) = &method.description {
        writeln!(out, "\t/// {desc}").unwrap();
    }

    // Signature
    write!(out, "\tpub async fn {}(&self", method.name).unwrap();

    // Path params as direct arguments
    for param in &method.path_params {
        write!(out, ", {}: {}", param.name, param.rust_type).unwrap();
    }

    // Query params struct
    if method.has_params {
        write!(out, ", params: Option<&{prefix}Params>").unwrap();
    }

    // Body struct
    if method.has_body {
        write!(out, ", body: Option<&{prefix}Body>").unwrap();
    }

    if method.response_is_text {
        writeln!(out, ") -> Result<String, LolzteamError> {{").unwrap();
    } else {
        writeln!(out, ") -> Result<{prefix}Response, LolzteamError> {{").unwrap();
    }

    // Build path string
    let has_path_params = !method.path_params.is_empty();
    if has_path_params {
        // For raw identifiers (r#type), bind to a clean local variable first
        let has_raw_ident = method.path_params.iter().any(|p| p.name.starts_with("r#"));
        if has_raw_ident {
            for param in &method.path_params {
                if param.name.starts_with("r#") {
                    let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
                    // Use a prefixed local to avoid keyword conflict
                    writeln!(out, "\t\tlet param_{clean} = {0};", param.name).unwrap();
                }
            }
        }
        let format_str = build_path_format_with_raw_prefix(&method.path, &method.path_params);
        writeln!(out, "\t\tlet path = format!(\"{format_str}\");").unwrap();
    }

    // Build query vec
    if method.has_params {
        writeln!(out, "\t\tlet mut query = Vec::new();").unwrap();
        writeln!(out, "\t\tif let Some(p) = params {{").unwrap();
        for param in &method.query_params {
            emit_param_push(out, "query", param, "\t\t\t");
        }
        writeln!(out, "\t\t}}").unwrap();
    }

    // Build body vec / parts depending on encoding
    match method.body_encoding {
        BodyEncoding::Multipart if method.has_body => {
            writeln!(out, "\t\tlet mut parts = Vec::new();").unwrap();
            writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
            for param in &method.body_params {
                emit_multipart_part_push(out, param, "\t\t\t");
            }
            writeln!(out, "\t\t}}").unwrap();
        }
        BodyEncoding::FormUrlEncoded if method.has_body => {
            writeln!(out, "\t\tlet mut form = Vec::new();").unwrap();
            writeln!(out, "\t\tif let Some(b) = body {{").unwrap();
            for param in &method.body_params {
                emit_param_push(out, "form", param, "\t\t\t");
            }
            writeln!(out, "\t\t}}").unwrap();
        }
        BodyEncoding::Json if method.has_body => {
            // JSON body is passed directly as a serializable struct — no vec building needed
        }
        _ => {}
    }

    // Call self.http.request(...)
    let path_arg = if has_path_params {
        "&path"
    } else {
        &format!("\"{}\"", method.path)
    };

    if method.response_is_text {
        let query_arg = if method.has_params {
            "if query.is_empty() { None } else { Some(query.as_slice()) }"
        } else {
            "None"
        };
        writeln!(
            out,
            "\t\tself.http.request_text(\"{}\", {path_arg}, {query_arg}).await",
            method.http_method
        )
        .unwrap();
    } else if method.body_encoding == BodyEncoding::Multipart {
        writeln!(
            out,
            "\t\tself.http.request_multipart(\"{}\", {path_arg}, parts).await",
            method.http_method
        )
        .unwrap();
    } else if method.body_encoding == BodyEncoding::Json {
        let query_arg = if method.has_params {
            "if query.is_empty() { None } else { Some(query.as_slice()) }"
        } else {
            "None"
        };
        let body_arg = if method.has_body {
            "body"
        } else {
            "None::<&()>"
        };
        writeln!(
            out,
            "\t\tself.http.request_json(\"{}\", {path_arg}, {query_arg}, {body_arg}).await",
            method.http_method
        )
        .unwrap();
    } else {
        let query_arg = if method.has_params {
            "if query.is_empty() { None } else { Some(query.as_slice()) }"
        } else {
            "None"
        };

        let body_arg = if method.has_body {
            "if form.is_empty() { None } else { Some(form.as_slice()) }"
        } else {
            "None"
        };

        writeln!(
            out,
            "\t\tself.http.request(\"{}\", {path_arg}, {query_arg}, {body_arg}).await",
            method.http_method
        )
        .unwrap();
    }
    writeln!(out, "\t}}").unwrap();
}

/// Emit code to push a parameter value into a Vec.
fn emit_param_push(out: &mut String, vec_name: &str, param: &ParamDef, indent: &str) {
    let api_name = &param.api_name;
    let field = &param.name;
    let variant = &param.param_value_variant;

    // Determine the correct accessor based on whether we're in body or query context
    let accessor = if vec_name == "form" { "b" } else { "p" };

    let base_type = param
        .rust_type
        .strip_prefix("Option<")
        .and_then(|s| s.strip_suffix('>'))
        .unwrap_or(&param.rust_type);

    // deepObject params: HashMap<String, T> → loop with format!("{api_name}[{key}]")
    if param.is_deep_object {
        let value_expr = match variant.as_str() {
            "Integer" => "ParamValue::Integer(*val)",
            "Float" => "ParamValue::Float(*val)",
            "Bool" => "ParamValue::Bool(*val)",
            _ => "ParamValue::String(val.to_string())",
        };
        if param.required {
            writeln!(out, "{indent}for (key, val) in &{accessor}.{field} {{").unwrap();
            writeln!(
                out,
                "{indent}\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
            )
            .unwrap();
            writeln!(out, "{indent}}}").unwrap();
        } else {
            writeln!(out, "{indent}if let Some(ref map) = {accessor}.{field} {{").unwrap();
            writeln!(out, "{indent}\tfor (key, val) in map {{").unwrap();
            writeln!(
                out,
                "{indent}\t\t{vec_name}.push((format!(\"{api_name}[{{key}}]\"), {value_expr}));"
            )
            .unwrap();
            writeln!(out, "{indent}\t}}").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        }
        return;
    }

    let is_vec = base_type.starts_with("Vec<");

    if is_vec {
        // For Vec types, push each element as a separate param
        if param.required {
            writeln!(out, "{indent}for item in &{accessor}.{field} {{").unwrap();
            writeln!(
				out,
				"{indent}\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
            .unwrap();
            writeln!(out, "{indent}}}").unwrap();
        } else {
            writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
            writeln!(out, "{indent}\tfor item in v {{").unwrap();
            writeln!(
				out,
				"{indent}\t\t{vec_name}.push((\"{api_name}\".into(), ParamValue::String(item.to_string())));"
			)
            .unwrap();
            writeln!(out, "{indent}\t}}").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        }
        return;
    }

    // For serde_json::Value types, always use .to_string()
    let is_json_value = base_type == "serde_json::Value";
    let is_string_or_int = base_type == "StringOrInt";

    if is_string_or_int {
        // StringOrInt needs match arms for ParamValue conversion
        if param.required {
            writeln!(out, "{indent}match &{accessor}.{field} {{").unwrap();
            writeln!(out, "{indent}\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
            writeln!(out, "{indent}\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        } else {
            writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
            writeln!(out, "{indent}\tmatch v {{").unwrap();
            writeln!(out, "{indent}\t\tStringOrInt::String(s) => {vec_name}.push((\"{api_name}\".into(), ParamValue::String(s.clone()))),").unwrap();
            writeln!(out, "{indent}\t\tStringOrInt::Int(n) => {vec_name}.push((\"{api_name}\".into(), ParamValue::Integer(*n))),").unwrap();
            writeln!(out, "{indent}\t}}").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        }
        return;
    }

    if param.required {
        let value_expr = if is_json_value {
            format!("ParamValue::String({accessor}.{field}.to_string())")
        } else {
            match variant.as_str() {
                "String" => format!("ParamValue::String({accessor}.{field}.clone())"),
                "Integer" => format!("ParamValue::Integer({accessor}.{field})"),
                "Float" => format!("ParamValue::Float({accessor}.{field})"),
                "Bool" => format!("ParamValue::Bool({accessor}.{field})"),
                _ => format!("ParamValue::String({accessor}.{field}.to_string())"),
            }
        };
        writeln!(
            out,
            "{indent}{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
        )
        .unwrap();
    } else {
        writeln!(out, "{indent}if let Some(ref v) = {accessor}.{field} {{").unwrap();
        let value_expr = if is_json_value {
            "ParamValue::String(v.to_string())".to_string()
        } else {
            match variant.as_str() {
                "String" => "ParamValue::String(v.clone())".to_string(),
                "Integer" => "ParamValue::Integer(*v)".to_string(),
                "Float" => "ParamValue::Float(*v)".to_string(),
                "Bool" => "ParamValue::Bool(*v)".to_string(),
                _ => "ParamValue::String(v.to_string())".to_string(),
            }
        };
        writeln!(
            out,
            "{indent}\t{vec_name}.push((\"{api_name}\".into(), {value_expr}));"
        )
        .unwrap();
        writeln!(out, "{indent}}}").unwrap();
    }
}

/// Emit code to push a multipart part into a Vec<MultipartPart>.
fn emit_multipart_part_push(out: &mut String, param: &ParamDef, indent: &str) {
    let api_name = &param.api_name;
    let field = &param.name;

    if param.is_binary {
        // Binary field → MultipartPart::File
        if param.required {
            writeln!(out, "{indent}parts.push(MultipartPart::File {{").unwrap();
            writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
            writeln!(out, "{indent}\tdata: b.{field}.clone(),").unwrap();
            writeln!(out, "{indent}\tfilename: Some(\"{api_name}\".to_string()),").unwrap();
            writeln!(
                out,
                "{indent}\tmime_type: Some(\"application/octet-stream\".to_string()),"
            )
            .unwrap();
            writeln!(out, "{indent}}});").unwrap();
        } else {
            writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
            writeln!(out, "{indent}\tparts.push(MultipartPart::File {{").unwrap();
            writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
            writeln!(out, "{indent}\t\tdata: v.clone(),").unwrap();
            writeln!(
                out,
                "{indent}\t\tfilename: Some(\"{api_name}\".to_string()),"
            )
            .unwrap();
            writeln!(
                out,
                "{indent}\t\tmime_type: Some(\"application/octet-stream\".to_string()),"
            )
            .unwrap();
            writeln!(out, "{indent}\t}});").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        }
    } else {
        // Text field → MultipartPart::Text
        let base_type = param
            .rust_type
            .strip_prefix("Option<")
            .and_then(|s| s.strip_suffix('>'))
            .unwrap_or(&param.rust_type);
        let is_vec = base_type.starts_with("Vec<");

        if param.required {
            let value_expr = if is_vec {
                // Vec<String> → join with space (spaceDelimited encoding)
                format!("b.{field}.join(\" \")")
            } else {
                match param.param_value_variant.as_str() {
                    "String" => format!("b.{field}.clone()"),
                    _ => format!("b.{field}.to_string()"),
                }
            };
            writeln!(out, "{indent}parts.push(MultipartPart::Text {{").unwrap();
            writeln!(out, "{indent}\tname: \"{api_name}\".to_string(),").unwrap();
            writeln!(out, "{indent}\tvalue: {value_expr},").unwrap();
            writeln!(out, "{indent}}});").unwrap();
        } else {
            writeln!(out, "{indent}if let Some(ref v) = b.{field} {{").unwrap();
            let value_expr = if is_vec {
                "v.join(\" \")".to_string()
            } else {
                match param.param_value_variant.as_str() {
                    "String" => "v.clone()".to_string(),
                    _ => "v.to_string()".to_string(),
                }
            };
            writeln!(out, "{indent}\tparts.push(MultipartPart::Text {{").unwrap();
            writeln!(out, "{indent}\t\tname: \"{api_name}\".to_string(),").unwrap();
            writeln!(out, "{indent}\t\tvalue: {value_expr},").unwrap();
            writeln!(out, "{indent}\t}});").unwrap();
            writeln!(out, "{indent}}}").unwrap();
        }
    }
}

/// Emit the client struct that composes all API groups.
pub fn emit_client(
    parsed: &ParseResult,
    client_name: &str,
    default_base_url: &str,
    default_rate_limit: u32,
    output_dir: &str,
) {
    let dir = Path::new(output_dir);
    fs::create_dir_all(dir).expect("failed to create output directory");

    let mut out = String::with_capacity(4096);
    writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use std::sync::Arc;").unwrap();
    writeln!(out).unwrap();
    writeln!(
		out,
		"use crate::runtime::{{ClientConfig, HttpClient, LolzteamError, RateLimitConfig, RetryConfig}};"
	)
    .unwrap();

    // Import group structs
    for group in &parsed.groups {
        writeln!(out, "use super::{}::{};", group.file_name, group.class_name).unwrap();
    }
    writeln!(out).unwrap();

    // Struct
    writeln!(out, "pub struct {client_name} {{").unwrap();
    for group in &parsed.groups {
        writeln!(out, "\t{}: {},", group.name, group.class_name).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Impl
    writeln!(out, "impl {client_name} {{").unwrap();

    // new(token)
    writeln!(out, "\t/// Create a new client with default configuration.").unwrap();
    writeln!(
        out,
        "\tpub fn new(token: impl Into<String>) -> Result<Self, LolzteamError> {{"
    )
    .unwrap();
    writeln!(out, "\t\tlet config = ClientConfig {{").unwrap();
    writeln!(out, "\t\t\ttoken: token.into(),").unwrap();
    writeln!(out, "\t\t\tbase_url: \"{default_base_url}\".to_string(),").unwrap();
    writeln!(out, "\t\t\tproxy: None,").unwrap();
    writeln!(out, "\t\t\tretry: RetryConfig::default(),").unwrap();
    writeln!(
        out,
        "\t\t\trate_limit: Some(RateLimitConfig {{ requests_per_minute: {default_rate_limit} }}),"
    )
    .unwrap();
    writeln!(out, "\t\t}};").unwrap();
    writeln!(out, "\t\tSelf::with_config(config)").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out).unwrap();

    // with_config(config)
    writeln!(out, "\t/// Create a new client with custom configuration.").unwrap();
    writeln!(
        out,
        "\tpub fn with_config(config: ClientConfig) -> Result<Self, LolzteamError> {{"
    )
    .unwrap();
    writeln!(out, "\t\tlet http = Arc::new(HttpClient::new(config)?);").unwrap();
    writeln!(out, "\t\tOk(Self {{").unwrap();
    for group in &parsed.groups {
        writeln!(
            out,
            "\t\t\t{}: {}::new(Arc::clone(&http)),",
            group.name, group.class_name
        )
        .unwrap();
    }
    writeln!(out, "\t\t}})").unwrap();
    writeln!(out, "\t}}").unwrap();

    // Accessor methods
    for group in &parsed.groups {
        writeln!(out).unwrap();
        writeln!(out, "\t/// Access the {} API group.", group.name).unwrap();
        writeln!(
            out,
            "\tpub fn {}(&self) -> &{} {{",
            group.name, group.class_name
        )
        .unwrap();
        writeln!(out, "\t\t&self.{}", group.name).unwrap();
        writeln!(out, "\t}}").unwrap();
    }

    writeln!(out, "}}").unwrap();

    let path = dir.join("client.rs");
    fs::write(&path, &out).expect("failed to write client.rs");
    eprintln!("  wrote {}", path.display());
}

/// Emit the mod.rs that re-exports everything.
pub fn emit_mod(parsed: &ParseResult, output_dir: &str) {
    let dir = Path::new(output_dir);
    fs::create_dir_all(dir).expect("failed to create output directory");

    let mut out = String::with_capacity(1024);
    writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "mod client;").unwrap();
    writeln!(out, "mod types;").unwrap();

    for group in &parsed.groups {
        writeln!(out, "mod {};", group.file_name).unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "pub use client::*;").unwrap();
    writeln!(out, "pub use types::*;").unwrap();

    for group in &parsed.groups {
        writeln!(out, "pub use {}::{};", group.file_name, group.class_name).unwrap();
    }

    let path = dir.join("mod.rs");
    fs::write(&path, &out).expect("failed to write mod.rs");
    eprintln!("  wrote {}", path.display());
}

/// Emit the top-level generated/mod.rs
pub fn emit_generated_mod(output_dir: &str) {
    let dir = Path::new(output_dir);
    fs::create_dir_all(dir).expect("failed to create output directory");

    let mut out = String::new();
    writeln!(out, "// Generated by codegen — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub mod forum;").unwrap();
    writeln!(out, "pub mod market;").unwrap();

    let path = dir.join("mod.rs");
    fs::write(&path, &out).expect("failed to write generated/mod.rs");
    eprintln!("  wrote {}", path.display());
}

/// Build a Rust format! string from a path template.
/// to reference the local variable we bound above.
fn build_path_format_with_raw_prefix(path: &str, path_params: &[ParamDef]) -> String {
    let mut result = path.to_string();
    for param in path_params {
        let placeholder = format!("{{{}}}", param.api_name);
        let var_name = if param.name.starts_with("r#") {
            let clean = param.name.strip_prefix("r#").unwrap_or(&param.name);
            format!("param_{clean}")
        } else {
            param.name.clone()
        };
        let replacement = format!("{{{var_name}}}");
        result = result.replace(&placeholder, &replacement);
    }
    result
}

/// Wrap a type in Option if not already optional.
fn optionalize(rust_type: &str) -> String {
    if rust_type.starts_with("Option<") {
        rust_type.to_string()
    } else {
        format!("Option<{rust_type}>")
    }
}
